// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.4
// source: web.proto

package web

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArticleListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           uint32                 `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Types         uint32                 `protobuf:"varint,4,opt,name=types,proto3" json:"types,omitempty"`
	Tid           uint32                 `protobuf:"varint,5,opt,name=tid,proto3" json:"tid,omitempty"`
	Keywords      string                 `protobuf:"bytes,6,opt,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleListReq) Reset() {
	*x = ArticleListReq{}
	mi := &file_web_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleListReq) ProtoMessage() {}

func (x *ArticleListReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleListReq.ProtoReflect.Descriptor instead.
func (*ArticleListReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{0}
}

func (x *ArticleListReq) GetCid() uint32 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *ArticleListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ArticleListReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ArticleListReq) GetTypes() uint32 {
	if x != nil {
		return x.Types
	}
	return 0
}

func (x *ArticleListReq) GetTid() uint32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *ArticleListReq) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

type ArticleListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	List          string                 `protobuf:"bytes,3,opt,name=list,proto3" json:"list,omitempty"`
	Total         uint32                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleListResp) Reset() {
	*x = ArticleListResp{}
	mi := &file_web_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleListResp) ProtoMessage() {}

func (x *ArticleListResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleListResp.ProtoReflect.Descriptor instead.
func (*ArticleListResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{1}
}

func (x *ArticleListResp) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ArticleListResp) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ArticleListResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

func (x *ArticleListResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ArticleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientIp      string                 `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"` // 客户端IP，用于浏览次数记录
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleReq) Reset() {
	*x = ArticleReq{}
	mi := &file_web_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleReq) ProtoMessage() {}

func (x *ArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleReq.ProtoReflect.Descriptor instead.
func (*ArticleReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{2}
}

func (x *ArticleReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticleReq) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type ArticleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleResp) Reset() {
	*x = ArticleResp{}
	mi := &file_web_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleResp) ProtoMessage() {}

func (x *ArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleResp.ProtoReflect.Descriptor instead.
func (*ArticleResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{3}
}

func (x *ArticleResp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ArticleLikeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleLikeReq) Reset() {
	*x = ArticleLikeReq{}
	mi := &file_web_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleLikeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleLikeReq) ProtoMessage() {}

func (x *ArticleLikeReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleLikeReq.ProtoReflect.Descriptor instead.
func (*ArticleLikeReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{4}
}

func (x *ArticleLikeReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ArticleLikeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleLikeResp) Reset() {
	*x = ArticleLikeResp{}
	mi := &file_web_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleLikeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleLikeResp) ProtoMessage() {}

func (x *ArticleLikeResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleLikeResp.ProtoReflect.Descriptor instead.
func (*ArticleLikeResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{5}
}

func (x *ArticleLikeResp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type CategoryListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryListReq) Reset() {
	*x = CategoryListReq{}
	mi := &file_web_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListReq) ProtoMessage() {}

func (x *CategoryListReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListReq.ProtoReflect.Descriptor instead.
func (*CategoryListReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{6}
}

func (x *CategoryListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CategoryListReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CategoryListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	List          string                 `protobuf:"bytes,3,opt,name=list,proto3" json:"list,omitempty"`
	Total         uint32                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryListResp) Reset() {
	*x = CategoryListResp{}
	mi := &file_web_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListResp) ProtoMessage() {}

func (x *CategoryListResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListResp.ProtoReflect.Descriptor instead.
func (*CategoryListResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{7}
}

func (x *CategoryListResp) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CategoryListResp) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *CategoryListResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

func (x *CategoryListResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ChatListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatListReq) Reset() {
	*x = ChatListReq{}
	mi := &file_web_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatListReq) ProtoMessage() {}

func (x *ChatListReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatListReq.ProtoReflect.Descriptor instead.
func (*ChatListReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{8}
}

func (x *ChatListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ChatListReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ChatListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	List          string                 `protobuf:"bytes,3,opt,name=list,proto3" json:"list,omitempty"`
	Total         uint32                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatListResp) Reset() {
	*x = ChatListResp{}
	mi := &file_web_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatListResp) ProtoMessage() {}

func (x *ChatListResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatListResp.ProtoReflect.Descriptor instead.
func (*ChatListResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{9}
}

func (x *ChatListResp) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ChatListResp) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ChatListResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

func (x *ChatListResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CommentListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentListReq) Reset() {
	*x = CommentListReq{}
	mi := &file_web_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentListReq) ProtoMessage() {}

func (x *CommentListReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentListReq.ProtoReflect.Descriptor instead.
func (*CommentListReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{10}
}

func (x *CommentListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CommentListReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CommentListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	List          string                 `protobuf:"bytes,3,opt,name=list,proto3" json:"list,omitempty"`
	Total         uint32                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentListResp) Reset() {
	*x = CommentListResp{}
	mi := &file_web_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentListResp) ProtoMessage() {}

func (x *CommentListResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentListResp.ProtoReflect.Descriptor instead.
func (*CommentListResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{11}
}

func (x *CommentListResp) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CommentListResp) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *CommentListResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

func (x *CommentListResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type OrderListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListReq) Reset() {
	*x = OrderListReq{}
	mi := &file_web_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListReq) ProtoMessage() {}

func (x *OrderListReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListReq.ProtoReflect.Descriptor instead.
func (*OrderListReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{12}
}

func (x *OrderListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *OrderListReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type OrderListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	List          string                 `protobuf:"bytes,3,opt,name=list,proto3" json:"list,omitempty"`
	Total         uint32                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListResp) Reset() {
	*x = OrderListResp{}
	mi := &file_web_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListResp) ProtoMessage() {}

func (x *OrderListResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListResp.ProtoReflect.Descriptor instead.
func (*OrderListResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{13}
}

func (x *OrderListResp) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *OrderListResp) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *OrderListResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

func (x *OrderListResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type OrderStatReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatReq) Reset() {
	*x = OrderStatReq{}
	mi := &file_web_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatReq) ProtoMessage() {}

func (x *OrderStatReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatReq.ProtoReflect.Descriptor instead.
func (*OrderStatReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{14}
}

type OrderStatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalAmount   float32                `protobuf:"fixed32,1,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	MonthAmount   float32                `protobuf:"fixed32,3,opt,name=month_amount,json=monthAmount,proto3" json:"month_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatResp) Reset() {
	*x = OrderStatResp{}
	mi := &file_web_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatResp) ProtoMessage() {}

func (x *OrderStatResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatResp.ProtoReflect.Descriptor instead.
func (*OrderStatResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{15}
}

func (x *OrderStatResp) GetTotalAmount() float32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *OrderStatResp) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *OrderStatResp) GetMonthAmount() float32 {
	if x != nil {
		return x.MonthAmount
	}
	return 0
}

type TagsListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagsListReq) Reset() {
	*x = TagsListReq{}
	mi := &file_web_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagsListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagsListReq) ProtoMessage() {}

func (x *TagsListReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagsListReq.ProtoReflect.Descriptor instead.
func (*TagsListReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{16}
}

type TagsListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          string                 `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagsListResp) Reset() {
	*x = TagsListResp{}
	mi := &file_web_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagsListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagsListResp) ProtoMessage() {}

func (x *TagsListResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagsListResp.ProtoReflect.Descriptor instead.
func (*TagsListResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{17}
}

func (x *TagsListResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

type ColumnListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnListReq) Reset() {
	*x = ColumnListReq{}
	mi := &file_web_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnListReq) ProtoMessage() {}

func (x *ColumnListReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnListReq.ProtoReflect.Descriptor instead.
func (*ColumnListReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{18}
}

type ColumnListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          string                 `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnListResp) Reset() {
	*x = ColumnListResp{}
	mi := &file_web_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnListResp) ProtoMessage() {}

func (x *ColumnListResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnListResp.ProtoReflect.Descriptor instead.
func (*ColumnListResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{19}
}

func (x *ColumnListResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

type BookListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Column        uint32                 `protobuf:"varint,3,opt,name=column,proto3" json:"column,omitempty"`
	Keywords      string                 `protobuf:"bytes,4,opt,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookListReq) Reset() {
	*x = BookListReq{}
	mi := &file_web_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookListReq) ProtoMessage() {}

func (x *BookListReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookListReq.ProtoReflect.Descriptor instead.
func (*BookListReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{20}
}

func (x *BookListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *BookListReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *BookListReq) GetColumn() uint32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *BookListReq) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

type BookListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	List          string                 `protobuf:"bytes,3,opt,name=list,proto3" json:"list,omitempty"`
	Total         uint32                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookListResp) Reset() {
	*x = BookListResp{}
	mi := &file_web_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookListResp) ProtoMessage() {}

func (x *BookListResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookListResp.ProtoReflect.Descriptor instead.
func (*BookListResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{21}
}

func (x *BookListResp) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *BookListResp) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *BookListResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

func (x *BookListResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type BookReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookReq) Reset() {
	*x = BookReq{}
	mi := &file_web_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookReq) ProtoMessage() {}

func (x *BookReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookReq.ProtoReflect.Descriptor instead.
func (*BookReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{22}
}

func (x *BookReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BookResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookResp) Reset() {
	*x = BookResp{}
	mi := &file_web_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookResp) ProtoMessage() {}

func (x *BookResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookResp.ProtoReflect.Descriptor instead.
func (*BookResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{23}
}

func (x *BookResp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type BookChapterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookChapterReq) Reset() {
	*x = BookChapterReq{}
	mi := &file_web_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookChapterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookChapterReq) ProtoMessage() {}

func (x *BookChapterReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookChapterReq.ProtoReflect.Descriptor instead.
func (*BookChapterReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{24}
}

func (x *BookChapterReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BookChapterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookChapterResp) Reset() {
	*x = BookChapterResp{}
	mi := &file_web_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookChapterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookChapterResp) ProtoMessage() {}

func (x *BookChapterResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookChapterResp.ProtoReflect.Descriptor instead.
func (*BookChapterResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{25}
}

func (x *BookChapterResp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type DocsListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int32                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Keywords      string                 `protobuf:"bytes,5,opt,name=keywords,proto3" json:"keywords,omitempty"`
	Page          int32                  `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Tag           string                 `protobuf:"bytes,8,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocsListReq) Reset() {
	*x = DocsListReq{}
	mi := &file_web_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocsListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsListReq) ProtoMessage() {}

func (x *DocsListReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsListReq.ProtoReflect.Descriptor instead.
func (*DocsListReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{26}
}

func (x *DocsListReq) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *DocsListReq) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *DocsListReq) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *DocsListReq) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

func (x *DocsListReq) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

func (x *DocsListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DocsListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *DocsListReq) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type DocsListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	List          string                 `protobuf:"bytes,3,opt,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocsListResp) Reset() {
	*x = DocsListResp{}
	mi := &file_web_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocsListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsListResp) ProtoMessage() {}

func (x *DocsListResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsListResp.ProtoReflect.Descriptor instead.
func (*DocsListResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{27}
}

func (x *DocsListResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DocsListResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *DocsListResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

func (x *DocsListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DocsCategoriesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocsCategoriesReq) Reset() {
	*x = DocsCategoriesReq{}
	mi := &file_web_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocsCategoriesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsCategoriesReq) ProtoMessage() {}

func (x *DocsCategoriesReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsCategoriesReq.ProtoReflect.Descriptor instead.
func (*DocsCategoriesReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{28}
}

type DocsCategoriesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          string                 `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocsCategoriesResp) Reset() {
	*x = DocsCategoriesResp{}
	mi := &file_web_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocsCategoriesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsCategoriesResp) ProtoMessage() {}

func (x *DocsCategoriesResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsCategoriesResp.ProtoReflect.Descriptor instead.
func (*DocsCategoriesResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{29}
}

func (x *DocsCategoriesResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

type DocsStatsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocsStatsReq) Reset() {
	*x = DocsStatsReq{}
	mi := &file_web_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocsStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsStatsReq) ProtoMessage() {}

func (x *DocsStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsStatsReq.ProtoReflect.Descriptor instead.
func (*DocsStatsReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{30}
}

type DocsStatsResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalDocs       int64                  `protobuf:"varint,1,opt,name=total_docs,json=totalDocs,proto3" json:"total_docs,omitempty"`
	TotalCategories int64                  `protobuf:"varint,2,opt,name=total_categories,json=totalCategories,proto3" json:"total_categories,omitempty"`
	TotalViews      int64                  `protobuf:"varint,3,opt,name=total_views,json=totalViews,proto3" json:"total_views,omitempty"`
	TotalLikes      int64                  `protobuf:"varint,4,opt,name=total_likes,json=totalLikes,proto3" json:"total_likes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DocsStatsResp) Reset() {
	*x = DocsStatsResp{}
	mi := &file_web_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocsStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsStatsResp) ProtoMessage() {}

func (x *DocsStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsStatsResp.ProtoReflect.Descriptor instead.
func (*DocsStatsResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{31}
}

func (x *DocsStatsResp) GetTotalDocs() int64 {
	if x != nil {
		return x.TotalDocs
	}
	return 0
}

func (x *DocsStatsResp) GetTotalCategories() int64 {
	if x != nil {
		return x.TotalCategories
	}
	return 0
}

func (x *DocsStatsResp) GetTotalViews() int64 {
	if x != nil {
		return x.TotalViews
	}
	return 0
}

func (x *DocsStatsResp) GetTotalLikes() int64 {
	if x != nil {
		return x.TotalLikes
	}
	return 0
}

type DocsPopularReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocsPopularReq) Reset() {
	*x = DocsPopularReq{}
	mi := &file_web_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocsPopularReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsPopularReq) ProtoMessage() {}

func (x *DocsPopularReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsPopularReq.ProtoReflect.Descriptor instead.
func (*DocsPopularReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{32}
}

func (x *DocsPopularReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DocsPopularResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          string                 `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocsPopularResp) Reset() {
	*x = DocsPopularResp{}
	mi := &file_web_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocsPopularResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsPopularResp) ProtoMessage() {}

func (x *DocsPopularResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsPopularResp.ProtoReflect.Descriptor instead.
func (*DocsPopularResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{33}
}

func (x *DocsPopularResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

type DocsLatestReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocsLatestReq) Reset() {
	*x = DocsLatestReq{}
	mi := &file_web_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocsLatestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsLatestReq) ProtoMessage() {}

func (x *DocsLatestReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsLatestReq.ProtoReflect.Descriptor instead.
func (*DocsLatestReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{34}
}

func (x *DocsLatestReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DocsLatestResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          string                 `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocsLatestResp) Reset() {
	*x = DocsLatestResp{}
	mi := &file_web_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocsLatestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsLatestResp) ProtoMessage() {}

func (x *DocsLatestResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsLatestResp.ProtoReflect.Descriptor instead.
func (*DocsLatestResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{35}
}

func (x *DocsLatestResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

type DocsTagsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocsTagsReq) Reset() {
	*x = DocsTagsReq{}
	mi := &file_web_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocsTagsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsTagsReq) ProtoMessage() {}

func (x *DocsTagsReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsTagsReq.ProtoReflect.Descriptor instead.
func (*DocsTagsReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{36}
}

type DocsTagsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          string                 `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocsTagsResp) Reset() {
	*x = DocsTagsResp{}
	mi := &file_web_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocsTagsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsTagsResp) ProtoMessage() {}

func (x *DocsTagsResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsTagsResp.ProtoReflect.Descriptor instead.
func (*DocsTagsResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{37}
}

func (x *DocsTagsResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

var File_web_proto protoreflect.FileDescriptor

const file_web_proto_rawDesc = "" +
	"\n" +
	"\tweb.proto\x12\x03web\"\x97\x01\n" +
	"\x0eArticleListReq\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\rR\x03cid\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\x12\x14\n" +
	"\x05types\x18\x04 \x01(\rR\x05types\x12\x10\n" +
	"\x03tid\x18\x05 \x01(\rR\x03tid\x12\x1a\n" +
	"\bkeywords\x18\x06 \x01(\tR\bkeywords\"l\n" +
	"\x0fArticleListResp\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x12\n" +
	"\x04list\x18\x03 \x01(\tR\x04list\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\"9\n" +
	"\n" +
	"ArticleReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\"!\n" +
	"\vArticleResp\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\" \n" +
	"\x0eArticleLikeReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"%\n" +
	"\x0fArticleLikeResp\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"B\n" +
	"\x0fCategoryListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\"m\n" +
	"\x10CategoryListResp\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x12\n" +
	"\x04list\x18\x03 \x01(\tR\x04list\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\">\n" +
	"\vChatListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\"i\n" +
	"\fChatListResp\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x12\n" +
	"\x04list\x18\x03 \x01(\tR\x04list\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\"A\n" +
	"\x0eCommentListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\"l\n" +
	"\x0fCommentListResp\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x12\n" +
	"\x04list\x18\x03 \x01(\tR\x04list\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\"?\n" +
	"\fOrderListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\"j\n" +
	"\rOrderListResp\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x12\n" +
	"\x04list\x18\x03 \x01(\tR\x04list\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\"\x0e\n" +
	"\fOrderStatReq\"k\n" +
	"\rOrderStatResp\x12!\n" +
	"\ftotal_amount\x18\x01 \x01(\x02R\vtotalAmount\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12!\n" +
	"\fmonth_amount\x18\x03 \x01(\x02R\vmonthAmount\"\r\n" +
	"\vTagsListReq\"\"\n" +
	"\fTagsListResp\x12\x12\n" +
	"\x04list\x18\x01 \x01(\tR\x04list\"\x0f\n" +
	"\rColumnListReq\"$\n" +
	"\x0eColumnListResp\x12\x12\n" +
	"\x04list\x18\x01 \x01(\tR\x04list\"r\n" +
	"\vBookListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x16\n" +
	"\x06column\x18\x03 \x01(\rR\x06column\x12\x1a\n" +
	"\bkeywords\x18\x04 \x01(\tR\bkeywords\"i\n" +
	"\fBookListResp\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x12\n" +
	"\x04list\x18\x03 \x01(\tR\x04list\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\"\x19\n" +
	"\aBookReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x1e\n" +
	"\bBookResp\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\" \n" +
	"\x0eBookChapterReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"%\n" +
	"\x0fBookChapterResp\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"\xdb\x01\n" +
	"\vDocsListReq\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x05R\n" +
	"categoryId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\tR\tsortOrder\x12\x1a\n" +
	"\bkeywords\x18\x05 \x01(\tR\bkeywords\x12\x12\n" +
	"\x04page\x18\x06 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x05R\bpageSize\x12\x10\n" +
	"\x03tag\x18\b \x01(\tR\x03tag\"i\n" +
	"\fDocsListResp\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04list\x18\x03 \x01(\tR\x04list\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"\x13\n" +
	"\x11DocsCategoriesReq\"(\n" +
	"\x12DocsCategoriesResp\x12\x12\n" +
	"\x04list\x18\x01 \x01(\tR\x04list\"\x0e\n" +
	"\fDocsStatsReq\"\x9b\x01\n" +
	"\rDocsStatsResp\x12\x1d\n" +
	"\n" +
	"total_docs\x18\x01 \x01(\x03R\ttotalDocs\x12)\n" +
	"\x10total_categories\x18\x02 \x01(\x03R\x0ftotalCategories\x12\x1f\n" +
	"\vtotal_views\x18\x03 \x01(\x03R\n" +
	"totalViews\x12\x1f\n" +
	"\vtotal_likes\x18\x04 \x01(\x03R\n" +
	"totalLikes\"&\n" +
	"\x0eDocsPopularReq\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"%\n" +
	"\x0fDocsPopularResp\x12\x12\n" +
	"\x04list\x18\x01 \x01(\tR\x04list\"%\n" +
	"\rDocsLatestReq\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"$\n" +
	"\x0eDocsLatestResp\x12\x12\n" +
	"\x04list\x18\x01 \x01(\tR\x04list\"\r\n" +
	"\vDocsTagsReq\"\"\n" +
	"\fDocsTagsResp\x12\x12\n" +
	"\x04list\x18\x01 \x01(\tR\x04list2\xf9\a\n" +
	"\x03Web\x128\n" +
	"\vArticleList\x12\x13.web.ArticleListReq\x1a\x14.web.ArticleListResp\x12,\n" +
	"\aArticle\x12\x0f.web.ArticleReq\x1a\x10.web.ArticleResp\x128\n" +
	"\vArticleLike\x12\x13.web.ArticleLikeReq\x1a\x14.web.ArticleLikeResp\x12;\n" +
	"\fCategoryList\x12\x14.web.CategoryListReq\x1a\x15.web.CategoryListResp\x12/\n" +
	"\bChatList\x12\x10.web.ChatListReq\x1a\x11.web.ChatListResp\x128\n" +
	"\vCommentList\x12\x13.web.CommentListReq\x1a\x14.web.CommentListResp\x122\n" +
	"\tOrderList\x12\x11.web.OrderListReq\x1a\x12.web.OrderListResp\x122\n" +
	"\tOrderStat\x12\x11.web.OrderStatReq\x1a\x12.web.OrderStatResp\x12/\n" +
	"\bTagsList\x12\x10.web.TagsListReq\x1a\x11.web.TagsListResp\x125\n" +
	"\n" +
	"ColumnList\x12\x12.web.ColumnListReq\x1a\x13.web.ColumnListResp\x12/\n" +
	"\bBookList\x12\x10.web.BookListReq\x1a\x11.web.BookListResp\x12#\n" +
	"\x04Book\x12\f.web.BookReq\x1a\r.web.BookResp\x128\n" +
	"\vBookChapter\x12\x13.web.BookChapterReq\x1a\x14.web.BookChapterResp\x12/\n" +
	"\bDocsList\x12\x10.web.DocsListReq\x1a\x11.web.DocsListResp\x12A\n" +
	"\x0eDocsCategories\x12\x16.web.DocsCategoriesReq\x1a\x17.web.DocsCategoriesResp\x122\n" +
	"\tDocsStats\x12\x11.web.DocsStatsReq\x1a\x12.web.DocsStatsResp\x128\n" +
	"\vDocsPopular\x12\x13.web.DocsPopularReq\x1a\x14.web.DocsPopularResp\x125\n" +
	"\n" +
	"DocsLatest\x12\x12.web.DocsLatestReq\x1a\x13.web.DocsLatestResp\x12/\n" +
	"\bDocsTags\x12\x10.web.DocsTagsReq\x1a\x11.web.DocsTagsRespB\aZ\x05./webb\x06proto3"

var (
	file_web_proto_rawDescOnce sync.Once
	file_web_proto_rawDescData []byte
)

func file_web_proto_rawDescGZIP() []byte {
	file_web_proto_rawDescOnce.Do(func() {
		file_web_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_web_proto_rawDesc), len(file_web_proto_rawDesc)))
	})
	return file_web_proto_rawDescData
}

var file_web_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_web_proto_goTypes = []any{
	(*ArticleListReq)(nil),     // 0: web.ArticleListReq
	(*ArticleListResp)(nil),    // 1: web.ArticleListResp
	(*ArticleReq)(nil),         // 2: web.ArticleReq
	(*ArticleResp)(nil),        // 3: web.ArticleResp
	(*ArticleLikeReq)(nil),     // 4: web.ArticleLikeReq
	(*ArticleLikeResp)(nil),    // 5: web.ArticleLikeResp
	(*CategoryListReq)(nil),    // 6: web.CategoryListReq
	(*CategoryListResp)(nil),   // 7: web.CategoryListResp
	(*ChatListReq)(nil),        // 8: web.ChatListReq
	(*ChatListResp)(nil),       // 9: web.ChatListResp
	(*CommentListReq)(nil),     // 10: web.CommentListReq
	(*CommentListResp)(nil),    // 11: web.CommentListResp
	(*OrderListReq)(nil),       // 12: web.OrderListReq
	(*OrderListResp)(nil),      // 13: web.OrderListResp
	(*OrderStatReq)(nil),       // 14: web.OrderStatReq
	(*OrderStatResp)(nil),      // 15: web.OrderStatResp
	(*TagsListReq)(nil),        // 16: web.TagsListReq
	(*TagsListResp)(nil),       // 17: web.TagsListResp
	(*ColumnListReq)(nil),      // 18: web.ColumnListReq
	(*ColumnListResp)(nil),     // 19: web.ColumnListResp
	(*BookListReq)(nil),        // 20: web.BookListReq
	(*BookListResp)(nil),       // 21: web.BookListResp
	(*BookReq)(nil),            // 22: web.BookReq
	(*BookResp)(nil),           // 23: web.BookResp
	(*BookChapterReq)(nil),     // 24: web.BookChapterReq
	(*BookChapterResp)(nil),    // 25: web.BookChapterResp
	(*DocsListReq)(nil),        // 26: web.DocsListReq
	(*DocsListResp)(nil),       // 27: web.DocsListResp
	(*DocsCategoriesReq)(nil),  // 28: web.DocsCategoriesReq
	(*DocsCategoriesResp)(nil), // 29: web.DocsCategoriesResp
	(*DocsStatsReq)(nil),       // 30: web.DocsStatsReq
	(*DocsStatsResp)(nil),      // 31: web.DocsStatsResp
	(*DocsPopularReq)(nil),     // 32: web.DocsPopularReq
	(*DocsPopularResp)(nil),    // 33: web.DocsPopularResp
	(*DocsLatestReq)(nil),      // 34: web.DocsLatestReq
	(*DocsLatestResp)(nil),     // 35: web.DocsLatestResp
	(*DocsTagsReq)(nil),        // 36: web.DocsTagsReq
	(*DocsTagsResp)(nil),       // 37: web.DocsTagsResp
}
var file_web_proto_depIdxs = []int32{
	0,  // 0: web.Web.ArticleList:input_type -> web.ArticleListReq
	2,  // 1: web.Web.Article:input_type -> web.ArticleReq
	4,  // 2: web.Web.ArticleLike:input_type -> web.ArticleLikeReq
	6,  // 3: web.Web.CategoryList:input_type -> web.CategoryListReq
	8,  // 4: web.Web.ChatList:input_type -> web.ChatListReq
	10, // 5: web.Web.CommentList:input_type -> web.CommentListReq
	12, // 6: web.Web.OrderList:input_type -> web.OrderListReq
	14, // 7: web.Web.OrderStat:input_type -> web.OrderStatReq
	16, // 8: web.Web.TagsList:input_type -> web.TagsListReq
	18, // 9: web.Web.ColumnList:input_type -> web.ColumnListReq
	20, // 10: web.Web.BookList:input_type -> web.BookListReq
	22, // 11: web.Web.Book:input_type -> web.BookReq
	24, // 12: web.Web.BookChapter:input_type -> web.BookChapterReq
	26, // 13: web.Web.DocsList:input_type -> web.DocsListReq
	28, // 14: web.Web.DocsCategories:input_type -> web.DocsCategoriesReq
	30, // 15: web.Web.DocsStats:input_type -> web.DocsStatsReq
	32, // 16: web.Web.DocsPopular:input_type -> web.DocsPopularReq
	34, // 17: web.Web.DocsLatest:input_type -> web.DocsLatestReq
	36, // 18: web.Web.DocsTags:input_type -> web.DocsTagsReq
	1,  // 19: web.Web.ArticleList:output_type -> web.ArticleListResp
	3,  // 20: web.Web.Article:output_type -> web.ArticleResp
	5,  // 21: web.Web.ArticleLike:output_type -> web.ArticleLikeResp
	7,  // 22: web.Web.CategoryList:output_type -> web.CategoryListResp
	9,  // 23: web.Web.ChatList:output_type -> web.ChatListResp
	11, // 24: web.Web.CommentList:output_type -> web.CommentListResp
	13, // 25: web.Web.OrderList:output_type -> web.OrderListResp
	15, // 26: web.Web.OrderStat:output_type -> web.OrderStatResp
	17, // 27: web.Web.TagsList:output_type -> web.TagsListResp
	19, // 28: web.Web.ColumnList:output_type -> web.ColumnListResp
	21, // 29: web.Web.BookList:output_type -> web.BookListResp
	23, // 30: web.Web.Book:output_type -> web.BookResp
	25, // 31: web.Web.BookChapter:output_type -> web.BookChapterResp
	27, // 32: web.Web.DocsList:output_type -> web.DocsListResp
	29, // 33: web.Web.DocsCategories:output_type -> web.DocsCategoriesResp
	31, // 34: web.Web.DocsStats:output_type -> web.DocsStatsResp
	33, // 35: web.Web.DocsPopular:output_type -> web.DocsPopularResp
	35, // 36: web.Web.DocsLatest:output_type -> web.DocsLatestResp
	37, // 37: web.Web.DocsTags:output_type -> web.DocsTagsResp
	19, // [19:38] is the sub-list for method output_type
	0,  // [0:19] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_web_proto_init() }
func file_web_proto_init() {
	if File_web_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_web_proto_rawDesc), len(file_web_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_web_proto_goTypes,
		DependencyIndexes: file_web_proto_depIdxs,
		MessageInfos:      file_web_proto_msgTypes,
	}.Build()
	File_web_proto = out.File
	file_web_proto_goTypes = nil
	file_web_proto_depIdxs = nil
}
