// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: web.proto

package web

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArticleListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid      uint32 `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Page     uint32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize uint32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Types    uint32 `protobuf:"varint,4,opt,name=types,proto3" json:"types,omitempty"`
	Tid      uint32 `protobuf:"varint,5,opt,name=tid,proto3" json:"tid,omitempty"`
	Keywords string `protobuf:"bytes,6,opt,name=keywords,proto3" json:"keywords,omitempty"`
}

func (x *ArticleListReq) Reset() {
	*x = ArticleListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArticleListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleListReq) ProtoMessage() {}

func (x *ArticleListReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleListReq.ProtoReflect.Descriptor instead.
func (*ArticleListReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{0}
}

func (x *ArticleListReq) GetCid() uint32 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *ArticleListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ArticleListReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ArticleListReq) GetTypes() uint32 {
	if x != nil {
		return x.Types
	}
	return 0
}

func (x *ArticleListReq) GetTid() uint32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *ArticleListReq) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

type ArticleListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	List     string `protobuf:"bytes,3,opt,name=list,proto3" json:"list,omitempty"`
	Total    uint32 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ArticleListResp) Reset() {
	*x = ArticleListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArticleListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleListResp) ProtoMessage() {}

func (x *ArticleListResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleListResp.ProtoReflect.Descriptor instead.
func (*ArticleListResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{1}
}

func (x *ArticleListResp) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ArticleListResp) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ArticleListResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

func (x *ArticleListResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ArticleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientIp string `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"` // 客户端IP，用于浏览次数记录
}

func (x *ArticleReq) Reset() {
	*x = ArticleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleReq) ProtoMessage() {}

func (x *ArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleReq.ProtoReflect.Descriptor instead.
func (*ArticleReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{2}
}

func (x *ArticleReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ArticleReq) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type ArticleResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ArticleResp) Reset() {
	*x = ArticleResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArticleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleResp) ProtoMessage() {}

func (x *ArticleResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleResp.ProtoReflect.Descriptor instead.
func (*ArticleResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{3}
}

func (x *ArticleResp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ArticleLikeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ArticleLikeReq) Reset() {
	*x = ArticleLikeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArticleLikeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleLikeReq) ProtoMessage() {}

func (x *ArticleLikeReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleLikeReq.ProtoReflect.Descriptor instead.
func (*ArticleLikeReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{4}
}

func (x *ArticleLikeReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ArticleLikeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ArticleLikeResp) Reset() {
	*x = ArticleLikeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArticleLikeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleLikeResp) ProtoMessage() {}

func (x *ArticleLikeResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleLikeResp.ProtoReflect.Descriptor instead.
func (*ArticleLikeResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{5}
}

func (x *ArticleLikeResp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type CategoryListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *CategoryListReq) Reset() {
	*x = CategoryListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListReq) ProtoMessage() {}

func (x *CategoryListReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListReq.ProtoReflect.Descriptor instead.
func (*CategoryListReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{6}
}

func (x *CategoryListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CategoryListReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CategoryListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	List     string `protobuf:"bytes,3,opt,name=list,proto3" json:"list,omitempty"`
	Total    uint32 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *CategoryListResp) Reset() {
	*x = CategoryListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListResp) ProtoMessage() {}

func (x *CategoryListResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListResp.ProtoReflect.Descriptor instead.
func (*CategoryListResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{7}
}

func (x *CategoryListResp) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CategoryListResp) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *CategoryListResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

func (x *CategoryListResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ChatListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *ChatListReq) Reset() {
	*x = ChatListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatListReq) ProtoMessage() {}

func (x *ChatListReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatListReq.ProtoReflect.Descriptor instead.
func (*ChatListReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{8}
}

func (x *ChatListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ChatListReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ChatListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	List     string `protobuf:"bytes,3,opt,name=list,proto3" json:"list,omitempty"`
	Total    uint32 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ChatListResp) Reset() {
	*x = ChatListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatListResp) ProtoMessage() {}

func (x *ChatListResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatListResp.ProtoReflect.Descriptor instead.
func (*ChatListResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{9}
}

func (x *ChatListResp) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ChatListResp) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ChatListResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

func (x *ChatListResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CommentListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *CommentListReq) Reset() {
	*x = CommentListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentListReq) ProtoMessage() {}

func (x *CommentListReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentListReq.ProtoReflect.Descriptor instead.
func (*CommentListReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{10}
}

func (x *CommentListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CommentListReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CommentListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	List     string `protobuf:"bytes,3,opt,name=list,proto3" json:"list,omitempty"`
	Total    uint32 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *CommentListResp) Reset() {
	*x = CommentListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentListResp) ProtoMessage() {}

func (x *CommentListResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentListResp.ProtoReflect.Descriptor instead.
func (*CommentListResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{11}
}

func (x *CommentListResp) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *CommentListResp) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *CommentListResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

func (x *CommentListResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type OrderListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *OrderListReq) Reset() {
	*x = OrderListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListReq) ProtoMessage() {}

func (x *OrderListReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListReq.ProtoReflect.Descriptor instead.
func (*OrderListReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{12}
}

func (x *OrderListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *OrderListReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type OrderListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	List     string `protobuf:"bytes,3,opt,name=list,proto3" json:"list,omitempty"`
	Total    uint32 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *OrderListResp) Reset() {
	*x = OrderListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListResp) ProtoMessage() {}

func (x *OrderListResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListResp.ProtoReflect.Descriptor instead.
func (*OrderListResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{13}
}

func (x *OrderListResp) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *OrderListResp) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *OrderListResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

func (x *OrderListResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type OrderStatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OrderStatReq) Reset() {
	*x = OrderStatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderStatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatReq) ProtoMessage() {}

func (x *OrderStatReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatReq.ProtoReflect.Descriptor instead.
func (*OrderStatReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{14}
}

type OrderStatResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalAmount float32 `protobuf:"fixed32,1,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Count       int64   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	MonthAmount float32 `protobuf:"fixed32,3,opt,name=month_amount,json=monthAmount,proto3" json:"month_amount,omitempty"`
}

func (x *OrderStatResp) Reset() {
	*x = OrderStatResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderStatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatResp) ProtoMessage() {}

func (x *OrderStatResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatResp.ProtoReflect.Descriptor instead.
func (*OrderStatResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{15}
}

func (x *OrderStatResp) GetTotalAmount() float32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *OrderStatResp) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *OrderStatResp) GetMonthAmount() float32 {
	if x != nil {
		return x.MonthAmount
	}
	return 0
}

type TagsListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TagsListReq) Reset() {
	*x = TagsListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagsListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagsListReq) ProtoMessage() {}

func (x *TagsListReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagsListReq.ProtoReflect.Descriptor instead.
func (*TagsListReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{16}
}

type TagsListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List string `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
}

func (x *TagsListResp) Reset() {
	*x = TagsListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagsListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagsListResp) ProtoMessage() {}

func (x *TagsListResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagsListResp.ProtoReflect.Descriptor instead.
func (*TagsListResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{17}
}

func (x *TagsListResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

type ColumnListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ColumnListReq) Reset() {
	*x = ColumnListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColumnListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnListReq) ProtoMessage() {}

func (x *ColumnListReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnListReq.ProtoReflect.Descriptor instead.
func (*ColumnListReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{18}
}

type ColumnListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List string `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
}

func (x *ColumnListResp) Reset() {
	*x = ColumnListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColumnListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnListResp) ProtoMessage() {}

func (x *ColumnListResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnListResp.ProtoReflect.Descriptor instead.
func (*ColumnListResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{19}
}

func (x *ColumnListResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

type BookListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Column   uint32 `protobuf:"varint,3,opt,name=column,proto3" json:"column,omitempty"`
	Keywords string `protobuf:"bytes,4,opt,name=keywords,proto3" json:"keywords,omitempty"`
}

func (x *BookListReq) Reset() {
	*x = BookListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookListReq) ProtoMessage() {}

func (x *BookListReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookListReq.ProtoReflect.Descriptor instead.
func (*BookListReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{20}
}

func (x *BookListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *BookListReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *BookListReq) GetColumn() uint32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *BookListReq) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

type BookListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     uint32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	List     string `protobuf:"bytes,3,opt,name=list,proto3" json:"list,omitempty"`
	Total    uint32 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *BookListResp) Reset() {
	*x = BookListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookListResp) ProtoMessage() {}

func (x *BookListResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookListResp.ProtoReflect.Descriptor instead.
func (*BookListResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{21}
}

func (x *BookListResp) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *BookListResp) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *BookListResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

func (x *BookListResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type BookReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BookReq) Reset() {
	*x = BookReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookReq) ProtoMessage() {}

func (x *BookReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookReq.ProtoReflect.Descriptor instead.
func (*BookReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{22}
}

func (x *BookReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BookResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BookResp) Reset() {
	*x = BookResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookResp) ProtoMessage() {}

func (x *BookResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookResp.ProtoReflect.Descriptor instead.
func (*BookResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{23}
}

func (x *BookResp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type BookChapterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BookChapterReq) Reset() {
	*x = BookChapterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookChapterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookChapterReq) ProtoMessage() {}

func (x *BookChapterReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookChapterReq.ProtoReflect.Descriptor instead.
func (*BookChapterReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{24}
}

func (x *BookChapterReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BookChapterResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *BookChapterResp) Reset() {
	*x = BookChapterResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookChapterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookChapterResp) ProtoMessage() {}

func (x *BookChapterResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookChapterResp.ProtoReflect.Descriptor instead.
func (*BookChapterResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{25}
}

func (x *BookChapterResp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type DocsListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CategoryId int32  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Level      string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	SortBy     string `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder  string `protobuf:"bytes,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Keywords   string `protobuf:"bytes,5,opt,name=keywords,proto3" json:"keywords,omitempty"`
	Page       int32  `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`
	PageSize   int32  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Tag        string `protobuf:"bytes,8,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *DocsListReq) Reset() {
	*x = DocsListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocsListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsListReq) ProtoMessage() {}

func (x *DocsListReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsListReq.ProtoReflect.Descriptor instead.
func (*DocsListReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{26}
}

func (x *DocsListReq) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *DocsListReq) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *DocsListReq) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *DocsListReq) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

func (x *DocsListReq) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

func (x *DocsListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DocsListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *DocsListReq) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type DocsListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	List     string `protobuf:"bytes,3,opt,name=list,proto3" json:"list,omitempty"`
	Total    int64  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *DocsListResp) Reset() {
	*x = DocsListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocsListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsListResp) ProtoMessage() {}

func (x *DocsListResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsListResp.ProtoReflect.Descriptor instead.
func (*DocsListResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{27}
}

func (x *DocsListResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DocsListResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *DocsListResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

func (x *DocsListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DocsCategoriesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DocsCategoriesReq) Reset() {
	*x = DocsCategoriesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocsCategoriesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsCategoriesReq) ProtoMessage() {}

func (x *DocsCategoriesReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsCategoriesReq.ProtoReflect.Descriptor instead.
func (*DocsCategoriesReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{28}
}

type DocsCategoriesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List string `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
}

func (x *DocsCategoriesResp) Reset() {
	*x = DocsCategoriesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocsCategoriesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsCategoriesResp) ProtoMessage() {}

func (x *DocsCategoriesResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsCategoriesResp.ProtoReflect.Descriptor instead.
func (*DocsCategoriesResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{29}
}

func (x *DocsCategoriesResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

type DocsStatsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DocsStatsReq) Reset() {
	*x = DocsStatsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocsStatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsStatsReq) ProtoMessage() {}

func (x *DocsStatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsStatsReq.ProtoReflect.Descriptor instead.
func (*DocsStatsReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{30}
}

type DocsStatsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalDocs       int64 `protobuf:"varint,1,opt,name=total_docs,json=totalDocs,proto3" json:"total_docs,omitempty"`
	TotalCategories int64 `protobuf:"varint,2,opt,name=total_categories,json=totalCategories,proto3" json:"total_categories,omitempty"`
	TotalViews      int64 `protobuf:"varint,3,opt,name=total_views,json=totalViews,proto3" json:"total_views,omitempty"`
	TotalLikes      int64 `protobuf:"varint,4,opt,name=total_likes,json=totalLikes,proto3" json:"total_likes,omitempty"`
}

func (x *DocsStatsResp) Reset() {
	*x = DocsStatsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocsStatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsStatsResp) ProtoMessage() {}

func (x *DocsStatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsStatsResp.ProtoReflect.Descriptor instead.
func (*DocsStatsResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{31}
}

func (x *DocsStatsResp) GetTotalDocs() int64 {
	if x != nil {
		return x.TotalDocs
	}
	return 0
}

func (x *DocsStatsResp) GetTotalCategories() int64 {
	if x != nil {
		return x.TotalCategories
	}
	return 0
}

func (x *DocsStatsResp) GetTotalViews() int64 {
	if x != nil {
		return x.TotalViews
	}
	return 0
}

func (x *DocsStatsResp) GetTotalLikes() int64 {
	if x != nil {
		return x.TotalLikes
	}
	return 0
}

type DocsPopularReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *DocsPopularReq) Reset() {
	*x = DocsPopularReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocsPopularReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsPopularReq) ProtoMessage() {}

func (x *DocsPopularReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsPopularReq.ProtoReflect.Descriptor instead.
func (*DocsPopularReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{32}
}

func (x *DocsPopularReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DocsPopularResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List string `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
}

func (x *DocsPopularResp) Reset() {
	*x = DocsPopularResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocsPopularResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsPopularResp) ProtoMessage() {}

func (x *DocsPopularResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsPopularResp.ProtoReflect.Descriptor instead.
func (*DocsPopularResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{33}
}

func (x *DocsPopularResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

type DocsLatestReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *DocsLatestReq) Reset() {
	*x = DocsLatestReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocsLatestReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsLatestReq) ProtoMessage() {}

func (x *DocsLatestReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsLatestReq.ProtoReflect.Descriptor instead.
func (*DocsLatestReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{34}
}

func (x *DocsLatestReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DocsLatestResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List string `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
}

func (x *DocsLatestResp) Reset() {
	*x = DocsLatestResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocsLatestResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsLatestResp) ProtoMessage() {}

func (x *DocsLatestResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsLatestResp.ProtoReflect.Descriptor instead.
func (*DocsLatestResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{35}
}

func (x *DocsLatestResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

type DocsTagsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DocsTagsReq) Reset() {
	*x = DocsTagsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocsTagsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsTagsReq) ProtoMessage() {}

func (x *DocsTagsReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsTagsReq.ProtoReflect.Descriptor instead.
func (*DocsTagsReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{36}
}

type DocsTagsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List string `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
}

func (x *DocsTagsResp) Reset() {
	*x = DocsTagsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[37]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocsTagsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsTagsResp) ProtoMessage() {}

func (x *DocsTagsResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[37]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsTagsResp.ProtoReflect.Descriptor instead.
func (*DocsTagsResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{37}
}

func (x *DocsTagsResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

type DocsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientIp string `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"` // 客户端IP，用于浏览次数记录
}

func (x *DocsReq) Reset() {
	*x = DocsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[38]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsReq) ProtoMessage() {}

func (x *DocsReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[38]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsReq.ProtoReflect.Descriptor instead.
func (*DocsReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{38}
}

func (x *DocsReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DocsReq) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type DocsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DocsResp) Reset() {
	*x = DocsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[39]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsResp) ProtoMessage() {}

func (x *DocsResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[39]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsResp.ProtoReflect.Descriptor instead.
func (*DocsResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{39}
}

func (x *DocsResp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type DocsUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *DocsUpdateReq) Reset() {
	*x = DocsUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[40]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocsUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsUpdateReq) ProtoMessage() {}

func (x *DocsUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[40]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsUpdateReq.ProtoReflect.Descriptor instead.
func (*DocsUpdateReq) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{40}
}

func (x *DocsUpdateReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DocsUpdateReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type DocsUpdateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Id     int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DocsUpdateResp) Reset() {
	*x = DocsUpdateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_web_proto_msgTypes[41]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocsUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocsUpdateResp) ProtoMessage() {}

func (x *DocsUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_web_proto_msgTypes[41]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocsUpdateResp.ProtoReflect.Descriptor instead.
func (*DocsUpdateResp) Descriptor() ([]byte, []int) {
	return file_web_proto_rawDescGZIP(), []int{41}
}

func (x *DocsUpdateResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DocsUpdateResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_web_proto protoreflect.FileDescriptor

var file_web_proto_rawDesc = []byte{
	0x0a, 0x09, 0x77, 0x65, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x77, 0x65, 0x62,
	0x22, 0x97, 0x01, 0x0a, 0x0e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67,
	0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x74, 0x69, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x6c, 0x0a, 0x0f, 0x41, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x39, 0x0a, 0x0a, 0x41, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x70, 0x22, 0x21, 0x0a, 0x0b, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x20, 0x0a, 0x0e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x25, 0x0a, 0x0f, 0x41, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x42, 0x0a, 0x0f, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x22, 0x6d, 0x0a, 0x10, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x22, 0x3e, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x22, 0x69, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x41, 0x0a,
	0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x22, 0x6c, 0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x3f,
	0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22,
	0x6a, 0x0a, 0x0d, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x0e, 0x0a, 0x0c, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x22, 0x6b, 0x0a, 0x0d, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x21, 0x0a, 0x0c,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x5f, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b, 0x6d, 0x6f, 0x6e,
	0x74, 0x68, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x54, 0x61, 0x67, 0x73,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x22, 0x0a, 0x0c, 0x54, 0x61, 0x67, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x43,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x24, 0x0a, 0x0e,
	0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x22, 0x72, 0x0a, 0x0b, 0x42, 0x6f, 0x6f, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65,
	0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x65,
	0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x69, 0x0a, 0x0c, 0x42, 0x6f, 0x6f, 0x6b, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61,
	0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70,
	0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x22, 0x19, 0x0a, 0x07, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1e, 0x0a, 0x08,
	0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x20, 0x0a, 0x0e,
	0x42, 0x6f, 0x6f, 0x6b, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x25,
	0x0a, 0x0f, 0x42, 0x6f, 0x6f, 0x6b, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xdb, 0x01, 0x0a, 0x0b, 0x44, 0x6f, 0x63, 0x73, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x17, 0x0a, 0x07,
	0x73, 0x6f, 0x72, 0x74, 0x5f, 0x62, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x6f, 0x72, 0x74, 0x42, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6f, 0x72, 0x74, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x74, 0x61, 0x67, 0x22, 0x69, 0x0a, 0x0c, 0x44, 0x6f, 0x63, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x13,
	0x0a, 0x11, 0x44, 0x6f, 0x63, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x22, 0x28, 0x0a, 0x12, 0x44, 0x6f, 0x63, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x0e, 0x0a,
	0x0c, 0x44, 0x6f, 0x63, 0x73, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x22, 0x9b, 0x01,
	0x0a, 0x0d, 0x44, 0x6f, 0x63, 0x73, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x64, 0x6f, 0x63, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x44, 0x6f, 0x63, 0x73, 0x12, 0x29,
	0x0a, 0x10, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x5f, 0x76, 0x69, 0x65, 0x77, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x56, 0x69, 0x65, 0x77, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x5f, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x22, 0x26, 0x0a, 0x0e, 0x44,
	0x6f, 0x63, 0x73, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x22, 0x25, 0x0a, 0x0f, 0x44, 0x6f, 0x63, 0x73, 0x50, 0x6f, 0x70, 0x75, 0x6c,
	0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x25, 0x0a, 0x0d, 0x44, 0x6f,
	0x63, 0x73, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x22, 0x24, 0x0a, 0x0e, 0x44, 0x6f, 0x63, 0x73, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x44, 0x6f, 0x63, 0x73, 0x54,
	0x61, 0x67, 0x73, 0x52, 0x65, 0x71, 0x22, 0x22, 0x0a, 0x0c, 0x44, 0x6f, 0x63, 0x73, 0x54, 0x61,
	0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x36, 0x0a, 0x07, 0x44, 0x6f,
	0x63, 0x73, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f,
	0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x70, 0x22, 0x1e, 0x0a, 0x08, 0x44, 0x6f, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x39, 0x0a, 0x0d, 0x44, 0x6f, 0x63, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x38, 0x0a,
	0x0e, 0x44, 0x6f, 0x63, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x32, 0xd5, 0x08, 0x0a, 0x03, 0x57, 0x65, 0x62, 0x12,
	0x38, 0x0a, 0x0b, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x13,
	0x2e, 0x77, 0x65, 0x62, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x07, 0x41, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x12, 0x0f, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x41, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x38, 0x0a, 0x0b, 0x41, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x12, 0x13, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x41, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x77, 0x65,
	0x62, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x3b, 0x0a, 0x0c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x14, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2f,
	0x0a, 0x08, 0x43, 0x68, 0x61, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x2e, 0x77, 0x65, 0x62,
	0x2e, 0x43, 0x68, 0x61, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x77,
	0x65, 0x62, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x38, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x13,
	0x2e, 0x77, 0x65, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x09, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x11, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x77, 0x65, 0x62, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a,
	0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x12, 0x11, 0x2e, 0x77, 0x65, 0x62,
	0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e,
	0x77, 0x65, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x2f, 0x0a, 0x08, 0x54, 0x61, 0x67, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x2e,
	0x77, 0x65, 0x62, 0x2e, 0x54, 0x61, 0x67, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x11, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x54, 0x61, 0x67, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x35, 0x0a, 0x0a, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x12, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x08, 0x42, 0x6f, 0x6f,
	0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x42, 0x6f, 0x6f, 0x6b,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x42, 0x6f,
	0x6f, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x04, 0x42, 0x6f,
	0x6f, 0x6b, 0x12, 0x0c, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71,
	0x1a, 0x0d, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x38, 0x0a, 0x0b, 0x42, 0x6f, 0x6f, 0x6b, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x12, 0x13,
	0x2e, 0x77, 0x65, 0x62, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x43, 0x68,
	0x61, 0x70, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x08, 0x44, 0x6f, 0x63,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x44, 0x6f, 0x63, 0x73,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x44, 0x6f,
	0x63, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x41, 0x0a, 0x0e, 0x44, 0x6f,
	0x63, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x77,
	0x65, 0x62, 0x2e, 0x44, 0x6f, 0x63, 0x73, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x44, 0x6f, 0x63, 0x73, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a,
	0x09, 0x44, 0x6f, 0x63, 0x73, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x11, 0x2e, 0x77, 0x65, 0x62,
	0x2e, 0x44, 0x6f, 0x63, 0x73, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e,
	0x77, 0x65, 0x62, 0x2e, 0x44, 0x6f, 0x63, 0x73, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x38, 0x0a, 0x0b, 0x44, 0x6f, 0x63, 0x73, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72,
	0x12, 0x13, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x44, 0x6f, 0x63, 0x73, 0x50, 0x6f, 0x70, 0x75, 0x6c,
	0x61, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x44, 0x6f, 0x63, 0x73,
	0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x35, 0x0a, 0x0a, 0x44,
	0x6f, 0x63, 0x73, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x12, 0x12, 0x2e, 0x77, 0x65, 0x62, 0x2e,
	0x44, 0x6f, 0x63, 0x73, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e,
	0x77, 0x65, 0x62, 0x2e, 0x44, 0x6f, 0x63, 0x73, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x2f, 0x0a, 0x08, 0x44, 0x6f, 0x63, 0x73, 0x54, 0x61, 0x67, 0x73, 0x12, 0x10,
	0x2e, 0x77, 0x65, 0x62, 0x2e, 0x44, 0x6f, 0x63, 0x73, 0x54, 0x61, 0x67, 0x73, 0x52, 0x65, 0x71,
	0x1a, 0x11, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x44, 0x6f, 0x63, 0x73, 0x54, 0x61, 0x67, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x04, 0x44, 0x6f, 0x63, 0x73, 0x12, 0x0c, 0x2e, 0x77, 0x65,
	0x62, 0x2e, 0x44, 0x6f, 0x63, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x77, 0x65, 0x62, 0x2e,
	0x44, 0x6f, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x35, 0x0a, 0x0a, 0x44, 0x6f, 0x63, 0x73,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x12, 0x2e, 0x77, 0x65, 0x62, 0x2e, 0x44, 0x6f, 0x63,
	0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x77, 0x65, 0x62,
	0x2e, 0x44, 0x6f, 0x63, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x42,
	0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x77, 0x65, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_web_proto_rawDescOnce sync.Once
	file_web_proto_rawDescData = file_web_proto_rawDesc
)

func file_web_proto_rawDescGZIP() []byte {
	file_web_proto_rawDescOnce.Do(func() {
		file_web_proto_rawDescData = protoimpl.X.CompressGZIP(file_web_proto_rawDescData)
	})
	return file_web_proto_rawDescData
}

var file_web_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_web_proto_goTypes = []interface{}{
	(*ArticleListReq)(nil),     // 0: web.ArticleListReq
	(*ArticleListResp)(nil),    // 1: web.ArticleListResp
	(*ArticleReq)(nil),         // 2: web.ArticleReq
	(*ArticleResp)(nil),        // 3: web.ArticleResp
	(*ArticleLikeReq)(nil),     // 4: web.ArticleLikeReq
	(*ArticleLikeResp)(nil),    // 5: web.ArticleLikeResp
	(*CategoryListReq)(nil),    // 6: web.CategoryListReq
	(*CategoryListResp)(nil),   // 7: web.CategoryListResp
	(*ChatListReq)(nil),        // 8: web.ChatListReq
	(*ChatListResp)(nil),       // 9: web.ChatListResp
	(*CommentListReq)(nil),     // 10: web.CommentListReq
	(*CommentListResp)(nil),    // 11: web.CommentListResp
	(*OrderListReq)(nil),       // 12: web.OrderListReq
	(*OrderListResp)(nil),      // 13: web.OrderListResp
	(*OrderStatReq)(nil),       // 14: web.OrderStatReq
	(*OrderStatResp)(nil),      // 15: web.OrderStatResp
	(*TagsListReq)(nil),        // 16: web.TagsListReq
	(*TagsListResp)(nil),       // 17: web.TagsListResp
	(*ColumnListReq)(nil),      // 18: web.ColumnListReq
	(*ColumnListResp)(nil),     // 19: web.ColumnListResp
	(*BookListReq)(nil),        // 20: web.BookListReq
	(*BookListResp)(nil),       // 21: web.BookListResp
	(*BookReq)(nil),            // 22: web.BookReq
	(*BookResp)(nil),           // 23: web.BookResp
	(*BookChapterReq)(nil),     // 24: web.BookChapterReq
	(*BookChapterResp)(nil),    // 25: web.BookChapterResp
	(*DocsListReq)(nil),        // 26: web.DocsListReq
	(*DocsListResp)(nil),       // 27: web.DocsListResp
	(*DocsCategoriesReq)(nil),  // 28: web.DocsCategoriesReq
	(*DocsCategoriesResp)(nil), // 29: web.DocsCategoriesResp
	(*DocsStatsReq)(nil),       // 30: web.DocsStatsReq
	(*DocsStatsResp)(nil),      // 31: web.DocsStatsResp
	(*DocsPopularReq)(nil),     // 32: web.DocsPopularReq
	(*DocsPopularResp)(nil),    // 33: web.DocsPopularResp
	(*DocsLatestReq)(nil),      // 34: web.DocsLatestReq
	(*DocsLatestResp)(nil),     // 35: web.DocsLatestResp
	(*DocsTagsReq)(nil),        // 36: web.DocsTagsReq
	(*DocsTagsResp)(nil),       // 37: web.DocsTagsResp
	(*DocsReq)(nil),            // 38: web.DocsReq
	(*DocsResp)(nil),           // 39: web.DocsResp
	(*DocsUpdateReq)(nil),      // 40: web.DocsUpdateReq
	(*DocsUpdateResp)(nil),     // 41: web.DocsUpdateResp
}
var file_web_proto_depIdxs = []int32{
	0,  // 0: web.Web.ArticleList:input_type -> web.ArticleListReq
	2,  // 1: web.Web.Article:input_type -> web.ArticleReq
	4,  // 2: web.Web.ArticleLike:input_type -> web.ArticleLikeReq
	6,  // 3: web.Web.CategoryList:input_type -> web.CategoryListReq
	8,  // 4: web.Web.ChatList:input_type -> web.ChatListReq
	10, // 5: web.Web.CommentList:input_type -> web.CommentListReq
	12, // 6: web.Web.OrderList:input_type -> web.OrderListReq
	14, // 7: web.Web.OrderStat:input_type -> web.OrderStatReq
	16, // 8: web.Web.TagsList:input_type -> web.TagsListReq
	18, // 9: web.Web.ColumnList:input_type -> web.ColumnListReq
	20, // 10: web.Web.BookList:input_type -> web.BookListReq
	22, // 11: web.Web.Book:input_type -> web.BookReq
	24, // 12: web.Web.BookChapter:input_type -> web.BookChapterReq
	26, // 13: web.Web.DocsList:input_type -> web.DocsListReq
	28, // 14: web.Web.DocsCategories:input_type -> web.DocsCategoriesReq
	30, // 15: web.Web.DocsStats:input_type -> web.DocsStatsReq
	32, // 16: web.Web.DocsPopular:input_type -> web.DocsPopularReq
	34, // 17: web.Web.DocsLatest:input_type -> web.DocsLatestReq
	36, // 18: web.Web.DocsTags:input_type -> web.DocsTagsReq
	38, // 19: web.Web.Docs:input_type -> web.DocsReq
	40, // 20: web.Web.DocsUpdate:input_type -> web.DocsUpdateReq
	1,  // 21: web.Web.ArticleList:output_type -> web.ArticleListResp
	3,  // 22: web.Web.Article:output_type -> web.ArticleResp
	5,  // 23: web.Web.ArticleLike:output_type -> web.ArticleLikeResp
	7,  // 24: web.Web.CategoryList:output_type -> web.CategoryListResp
	9,  // 25: web.Web.ChatList:output_type -> web.ChatListResp
	11, // 26: web.Web.CommentList:output_type -> web.CommentListResp
	13, // 27: web.Web.OrderList:output_type -> web.OrderListResp
	15, // 28: web.Web.OrderStat:output_type -> web.OrderStatResp
	17, // 29: web.Web.TagsList:output_type -> web.TagsListResp
	19, // 30: web.Web.ColumnList:output_type -> web.ColumnListResp
	21, // 31: web.Web.BookList:output_type -> web.BookListResp
	23, // 32: web.Web.Book:output_type -> web.BookResp
	25, // 33: web.Web.BookChapter:output_type -> web.BookChapterResp
	27, // 34: web.Web.DocsList:output_type -> web.DocsListResp
	29, // 35: web.Web.DocsCategories:output_type -> web.DocsCategoriesResp
	31, // 36: web.Web.DocsStats:output_type -> web.DocsStatsResp
	33, // 37: web.Web.DocsPopular:output_type -> web.DocsPopularResp
	35, // 38: web.Web.DocsLatest:output_type -> web.DocsLatestResp
	37, // 39: web.Web.DocsTags:output_type -> web.DocsTagsResp
	39, // 40: web.Web.Docs:output_type -> web.DocsResp
	41, // 41: web.Web.DocsUpdate:output_type -> web.DocsUpdateResp
	21, // [21:42] is the sub-list for method output_type
	0,  // [0:21] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_web_proto_init() }
func file_web_proto_init() {
	if File_web_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_web_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArticleListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArticleListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArticleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArticleResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArticleLikeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArticleLikeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoryListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoryListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommentListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommentListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderStatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderStatResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagsListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagsListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColumnListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColumnListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookChapterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookChapterResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocsListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocsListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocsCategoriesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocsCategoriesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocsStatsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocsStatsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocsPopularReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocsPopularResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocsLatestReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocsLatestResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[36].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocsTagsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[37].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocsTagsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[38].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[39].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[40].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocsUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_web_proto_msgTypes[41].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocsUpdateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_web_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_web_proto_goTypes,
		DependencyIndexes: file_web_proto_depIdxs,
		MessageInfos:      file_web_proto_msgTypes,
	}.Build()
	File_web_proto = out.File
	file_web_proto_rawDesc = nil
	file_web_proto_goTypes = nil
	file_web_proto_depIdxs = nil
}
