// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: web.proto

package web

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Web_ArticleList_FullMethodName    = "/web.Web/ArticleList"
	Web_Article_FullMethodName        = "/web.Web/Article"
	Web_ArticleLike_FullMethodName    = "/web.Web/ArticleLike"
	Web_CategoryList_FullMethodName   = "/web.Web/CategoryList"
	Web_ChatList_FullMethodName       = "/web.Web/ChatList"
	Web_CommentList_FullMethodName    = "/web.Web/CommentList"
	Web_OrderList_FullMethodName      = "/web.Web/OrderList"
	Web_TagsList_FullMethodName       = "/web.Web/TagsList"
	Web_ColumnList_FullMethodName     = "/web.Web/ColumnList"
	Web_BookList_FullMethodName       = "/web.Web/BookList"
	Web_Book_FullMethodName           = "/web.Web/Book"
	Web_BookChapter_FullMethodName    = "/web.Web/BookChapter"
	Web_DocsList_FullMethodName       = "/web.Web/DocsList"
	Web_DocsCategories_FullMethodName = "/web.Web/DocsCategories"
	Web_DocsStats_FullMethodName      = "/web.Web/DocsStats"
	Web_DocsPopular_FullMethodName    = "/web.Web/DocsPopular"
	Web_DocsLatest_FullMethodName     = "/web.Web/DocsLatest"
	Web_DocsTags_FullMethodName       = "/web.Web/DocsTags"
)

// WebClient is the client API for Web service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebClient interface {
	ArticleList(ctx context.Context, in *ArticleListReq, opts ...grpc.CallOption) (*ArticleListResp, error)
	Article(ctx context.Context, in *ArticleReq, opts ...grpc.CallOption) (*ArticleResp, error)
	ArticleLike(ctx context.Context, in *ArticleLikeReq, opts ...grpc.CallOption) (*ArticleLikeResp, error)
	CategoryList(ctx context.Context, in *CategoryListReq, opts ...grpc.CallOption) (*CategoryListResp, error)
	ChatList(ctx context.Context, in *ChatListReq, opts ...grpc.CallOption) (*ChatListResp, error)
	CommentList(ctx context.Context, in *CommentListReq, opts ...grpc.CallOption) (*CommentListResp, error)
	OrderList(ctx context.Context, in *OrderListReq, opts ...grpc.CallOption) (*OrderListResp, error)
	TagsList(ctx context.Context, in *TagsListReq, opts ...grpc.CallOption) (*TagsListResp, error)
	ColumnList(ctx context.Context, in *ColumnListReq, opts ...grpc.CallOption) (*ColumnListResp, error)
	BookList(ctx context.Context, in *BookListReq, opts ...grpc.CallOption) (*BookListResp, error)
	Book(ctx context.Context, in *BookReq, opts ...grpc.CallOption) (*BookResp, error)
	BookChapter(ctx context.Context, in *BookChapterReq, opts ...grpc.CallOption) (*BookChapterResp, error)
	DocsList(ctx context.Context, in *DocsListReq, opts ...grpc.CallOption) (*DocsListResp, error)
	DocsCategories(ctx context.Context, in *DocsCategoriesReq, opts ...grpc.CallOption) (*DocsCategoriesResp, error)
	DocsStats(ctx context.Context, in *DocsStatsReq, opts ...grpc.CallOption) (*DocsStatsResp, error)
	DocsPopular(ctx context.Context, in *DocsPopularReq, opts ...grpc.CallOption) (*DocsPopularResp, error)
	DocsLatest(ctx context.Context, in *DocsLatestReq, opts ...grpc.CallOption) (*DocsLatestResp, error)
	DocsTags(ctx context.Context, in *DocsTagsReq, opts ...grpc.CallOption) (*DocsTagsResp, error)
}

type webClient struct {
	cc grpc.ClientConnInterface
}

func NewWebClient(cc grpc.ClientConnInterface) WebClient {
	return &webClient{cc}
}

func (c *webClient) ArticleList(ctx context.Context, in *ArticleListReq, opts ...grpc.CallOption) (*ArticleListResp, error) {
	out := new(ArticleListResp)
	err := c.cc.Invoke(ctx, Web_ArticleList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) Article(ctx context.Context, in *ArticleReq, opts ...grpc.CallOption) (*ArticleResp, error) {
	out := new(ArticleResp)
	err := c.cc.Invoke(ctx, Web_Article_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) ArticleLike(ctx context.Context, in *ArticleLikeReq, opts ...grpc.CallOption) (*ArticleLikeResp, error) {
	out := new(ArticleLikeResp)
	err := c.cc.Invoke(ctx, Web_ArticleLike_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) CategoryList(ctx context.Context, in *CategoryListReq, opts ...grpc.CallOption) (*CategoryListResp, error) {
	out := new(CategoryListResp)
	err := c.cc.Invoke(ctx, Web_CategoryList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) ChatList(ctx context.Context, in *ChatListReq, opts ...grpc.CallOption) (*ChatListResp, error) {
	out := new(ChatListResp)
	err := c.cc.Invoke(ctx, Web_ChatList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) CommentList(ctx context.Context, in *CommentListReq, opts ...grpc.CallOption) (*CommentListResp, error) {
	out := new(CommentListResp)
	err := c.cc.Invoke(ctx, Web_CommentList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) OrderList(ctx context.Context, in *OrderListReq, opts ...grpc.CallOption) (*OrderListResp, error) {
	out := new(OrderListResp)
	err := c.cc.Invoke(ctx, Web_OrderList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) TagsList(ctx context.Context, in *TagsListReq, opts ...grpc.CallOption) (*TagsListResp, error) {
	out := new(TagsListResp)
	err := c.cc.Invoke(ctx, Web_TagsList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) ColumnList(ctx context.Context, in *ColumnListReq, opts ...grpc.CallOption) (*ColumnListResp, error) {
	out := new(ColumnListResp)
	err := c.cc.Invoke(ctx, Web_ColumnList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) BookList(ctx context.Context, in *BookListReq, opts ...grpc.CallOption) (*BookListResp, error) {
	out := new(BookListResp)
	err := c.cc.Invoke(ctx, Web_BookList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) Book(ctx context.Context, in *BookReq, opts ...grpc.CallOption) (*BookResp, error) {
	out := new(BookResp)
	err := c.cc.Invoke(ctx, Web_Book_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) BookChapter(ctx context.Context, in *BookChapterReq, opts ...grpc.CallOption) (*BookChapterResp, error) {
	out := new(BookChapterResp)
	err := c.cc.Invoke(ctx, Web_BookChapter_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) DocsList(ctx context.Context, in *DocsListReq, opts ...grpc.CallOption) (*DocsListResp, error) {
	out := new(DocsListResp)
	err := c.cc.Invoke(ctx, Web_DocsList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) DocsCategories(ctx context.Context, in *DocsCategoriesReq, opts ...grpc.CallOption) (*DocsCategoriesResp, error) {
	out := new(DocsCategoriesResp)
	err := c.cc.Invoke(ctx, Web_DocsCategories_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) DocsStats(ctx context.Context, in *DocsStatsReq, opts ...grpc.CallOption) (*DocsStatsResp, error) {
	out := new(DocsStatsResp)
	err := c.cc.Invoke(ctx, Web_DocsStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) DocsPopular(ctx context.Context, in *DocsPopularReq, opts ...grpc.CallOption) (*DocsPopularResp, error) {
	out := new(DocsPopularResp)
	err := c.cc.Invoke(ctx, Web_DocsPopular_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) DocsLatest(ctx context.Context, in *DocsLatestReq, opts ...grpc.CallOption) (*DocsLatestResp, error) {
	out := new(DocsLatestResp)
	err := c.cc.Invoke(ctx, Web_DocsLatest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webClient) DocsTags(ctx context.Context, in *DocsTagsReq, opts ...grpc.CallOption) (*DocsTagsResp, error) {
	out := new(DocsTagsResp)
	err := c.cc.Invoke(ctx, Web_DocsTags_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebServer is the server API for Web service.
// All implementations must embed UnimplementedWebServer
// for forward compatibility
type WebServer interface {
	ArticleList(context.Context, *ArticleListReq) (*ArticleListResp, error)
	Article(context.Context, *ArticleReq) (*ArticleResp, error)
	ArticleLike(context.Context, *ArticleLikeReq) (*ArticleLikeResp, error)
	CategoryList(context.Context, *CategoryListReq) (*CategoryListResp, error)
	ChatList(context.Context, *ChatListReq) (*ChatListResp, error)
	CommentList(context.Context, *CommentListReq) (*CommentListResp, error)
	OrderList(context.Context, *OrderListReq) (*OrderListResp, error)
	TagsList(context.Context, *TagsListReq) (*TagsListResp, error)
	ColumnList(context.Context, *ColumnListReq) (*ColumnListResp, error)
	BookList(context.Context, *BookListReq) (*BookListResp, error)
	Book(context.Context, *BookReq) (*BookResp, error)
	BookChapter(context.Context, *BookChapterReq) (*BookChapterResp, error)
	DocsList(context.Context, *DocsListReq) (*DocsListResp, error)
	DocsCategories(context.Context, *DocsCategoriesReq) (*DocsCategoriesResp, error)
	DocsStats(context.Context, *DocsStatsReq) (*DocsStatsResp, error)
	DocsPopular(context.Context, *DocsPopularReq) (*DocsPopularResp, error)
	DocsLatest(context.Context, *DocsLatestReq) (*DocsLatestResp, error)
	DocsTags(context.Context, *DocsTagsReq) (*DocsTagsResp, error)
	mustEmbedUnimplementedWebServer()
}

// UnimplementedWebServer must be embedded to have forward compatible implementations.
type UnimplementedWebServer struct {
}

func (UnimplementedWebServer) ArticleList(context.Context, *ArticleListReq) (*ArticleListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArticleList not implemented")
}
func (UnimplementedWebServer) Article(context.Context, *ArticleReq) (*ArticleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Article not implemented")
}
func (UnimplementedWebServer) ArticleLike(context.Context, *ArticleLikeReq) (*ArticleLikeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArticleLike not implemented")
}
func (UnimplementedWebServer) CategoryList(context.Context, *CategoryListReq) (*CategoryListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CategoryList not implemented")
}
func (UnimplementedWebServer) ChatList(context.Context, *ChatListReq) (*ChatListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChatList not implemented")
}
func (UnimplementedWebServer) CommentList(context.Context, *CommentListReq) (*CommentListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommentList not implemented")
}
func (UnimplementedWebServer) OrderList(context.Context, *OrderListReq) (*OrderListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderList not implemented")
}
func (UnimplementedWebServer) TagsList(context.Context, *TagsListReq) (*TagsListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TagsList not implemented")
}
func (UnimplementedWebServer) ColumnList(context.Context, *ColumnListReq) (*ColumnListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ColumnList not implemented")
}
func (UnimplementedWebServer) BookList(context.Context, *BookListReq) (*BookListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookList not implemented")
}
func (UnimplementedWebServer) Book(context.Context, *BookReq) (*BookResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Book not implemented")
}
func (UnimplementedWebServer) BookChapter(context.Context, *BookChapterReq) (*BookChapterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookChapter not implemented")
}
func (UnimplementedWebServer) DocsList(context.Context, *DocsListReq) (*DocsListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DocsList not implemented")
}
func (UnimplementedWebServer) DocsCategories(context.Context, *DocsCategoriesReq) (*DocsCategoriesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DocsCategories not implemented")
}
func (UnimplementedWebServer) DocsStats(context.Context, *DocsStatsReq) (*DocsStatsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DocsStats not implemented")
}
func (UnimplementedWebServer) DocsPopular(context.Context, *DocsPopularReq) (*DocsPopularResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DocsPopular not implemented")
}
func (UnimplementedWebServer) DocsLatest(context.Context, *DocsLatestReq) (*DocsLatestResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DocsLatest not implemented")
}
func (UnimplementedWebServer) DocsTags(context.Context, *DocsTagsReq) (*DocsTagsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DocsTags not implemented")
}
func (UnimplementedWebServer) mustEmbedUnimplementedWebServer() {}

// UnsafeWebServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebServer will
// result in compilation errors.
type UnsafeWebServer interface {
	mustEmbedUnimplementedWebServer()
}

func RegisterWebServer(s grpc.ServiceRegistrar, srv WebServer) {
	s.RegisterService(&Web_ServiceDesc, srv)
}

func _Web_ArticleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).ArticleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Web_ArticleList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).ArticleList(ctx, req.(*ArticleListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_Article_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).Article(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Web_Article_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).Article(ctx, req.(*ArticleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_ArticleLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleLikeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).ArticleLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Web_ArticleLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).ArticleLike(ctx, req.(*ArticleLikeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_CategoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoryListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).CategoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Web_CategoryList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).CategoryList(ctx, req.(*CategoryListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_ChatList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).ChatList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Web_ChatList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).ChatList(ctx, req.(*ChatListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_CommentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).CommentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Web_CommentList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).CommentList(ctx, req.(*CommentListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_OrderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).OrderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Web_OrderList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).OrderList(ctx, req.(*OrderListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_TagsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagsListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).TagsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Web_TagsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).TagsList(ctx, req.(*TagsListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_ColumnList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ColumnListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).ColumnList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Web_ColumnList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).ColumnList(ctx, req.(*ColumnListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_BookList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).BookList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Web_BookList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).BookList(ctx, req.(*BookListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_Book_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).Book(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Web_Book_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).Book(ctx, req.(*BookReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_BookChapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookChapterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).BookChapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Web_BookChapter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).BookChapter(ctx, req.(*BookChapterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_DocsList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocsListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).DocsList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Web_DocsList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).DocsList(ctx, req.(*DocsListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_DocsCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocsCategoriesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).DocsCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Web_DocsCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).DocsCategories(ctx, req.(*DocsCategoriesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_DocsStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocsStatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).DocsStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Web_DocsStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).DocsStats(ctx, req.(*DocsStatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_DocsPopular_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocsPopularReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).DocsPopular(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Web_DocsPopular_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).DocsPopular(ctx, req.(*DocsPopularReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_DocsLatest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocsLatestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).DocsLatest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Web_DocsLatest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).DocsLatest(ctx, req.(*DocsLatestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Web_DocsTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocsTagsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebServer).DocsTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Web_DocsTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebServer).DocsTags(ctx, req.(*DocsTagsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Web_ServiceDesc is the grpc.ServiceDesc for Web service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Web_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "web.Web",
	HandlerType: (*WebServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ArticleList",
			Handler:    _Web_ArticleList_Handler,
		},
		{
			MethodName: "Article",
			Handler:    _Web_Article_Handler,
		},
		{
			MethodName: "ArticleLike",
			Handler:    _Web_ArticleLike_Handler,
		},
		{
			MethodName: "CategoryList",
			Handler:    _Web_CategoryList_Handler,
		},
		{
			MethodName: "ChatList",
			Handler:    _Web_ChatList_Handler,
		},
		{
			MethodName: "CommentList",
			Handler:    _Web_CommentList_Handler,
		},
		{
			MethodName: "OrderList",
			Handler:    _Web_OrderList_Handler,
		},
		{
			MethodName: "TagsList",
			Handler:    _Web_TagsList_Handler,
		},
		{
			MethodName: "ColumnList",
			Handler:    _Web_ColumnList_Handler,
		},
		{
			MethodName: "BookList",
			Handler:    _Web_BookList_Handler,
		},
		{
			MethodName: "Book",
			Handler:    _Web_Book_Handler,
		},
		{
			MethodName: "BookChapter",
			Handler:    _Web_BookChapter_Handler,
		},
		{
			MethodName: "DocsList",
			Handler:    _Web_DocsList_Handler,
		},
		{
			MethodName: "DocsCategories",
			Handler:    _Web_DocsCategories_Handler,
		},
		{
			MethodName: "DocsStats",
			Handler:    _Web_DocsStats_Handler,
		},
		{
			MethodName: "DocsPopular",
			Handler:    _Web_DocsPopular_Handler,
		},
		{
			MethodName: "DocsLatest",
			Handler:    _Web_DocsLatest_Handler,
		},
		{
			MethodName: "DocsTags",
			Handler:    _Web_DocsTags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "web.proto",
}
