// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: web.proto

package server

import (
	"context"

	"lxtian-blog/rpc/web/internal/logic"
	"lxtian-blog/rpc/web/internal/svc"
	"lxtian-blog/rpc/web/web"
)

type WebServer struct {
	svcCtx *svc.ServiceContext
	web.UnimplementedWebServer
}

func NewWebServer(svcCtx *svc.ServiceContext) *WebServer {
	return &WebServer{
		svcCtx: svcCtx,
	}
}

func (s *WebServer) Ping(ctx context.Context, in *web.Request) (*web.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
