// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"

	"lxtian-blog/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 后台登录
				Method:  http.MethodPost,
				Path:    "/admin/login",
				Handler: LoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtMiddleware},
			[]rest.Route{
				{
					// 文章详情
					Method:  http.MethodGet,
					Path:    "/article/:id",
					Handler: ArticleHandler(serverCtx),
				},
				{
					// 文章保存
					Method:  http.MethodPost,
					Path:    "/article/save",
					Handler: ArticleSaveHandler(serverCtx),
				},
				{
					// 文章管理
					Method:  http.MethodGet,
					Path:    "/articles",
					Handler: ArticlesHandler(serverCtx),
				},
				{
					// 书单管理
					Method:  http.MethodGet,
					Path:    "/book",
					Handler: BooKHandler(serverCtx),
				},
				{
					// 书单章节
					Method:  http.MethodGet,
					Path:    "/book/chapter/:id",
					Handler: BookChapterHandler(serverCtx),
				},
				{
					// 书单详情
					Method:  http.MethodGet,
					Path:    "/book/chapter/detail/:id",
					Handler: ChapterDetailHandler(serverCtx),
				},
				{
					// 章节保存
					Method:  http.MethodPost,
					Path:    "/book/chapter/save",
					Handler: BookChapterSaveHandler(serverCtx),
				},
				{
					// 文章分类
					Method:  http.MethodGet,
					Path:    "/category",
					Handler: CategoryHandler(serverCtx),
				},
				{
					// 专栏列表
					Method:  http.MethodGet,
					Path:    "/column/list",
					Handler: ColumnListHandler(serverCtx),
				},
				{
					// 书单保存
					Method:  http.MethodPost,
					Path:    "/column/save",
					Handler: BookSaveHandler(serverCtx),
				},
				{
					// 用户信息
					Method:  http.MethodGet,
					Path:    "/info",
					Handler: InfoHandler(serverCtx),
				},
				{
					// 菜单保存
					Method:  http.MethodPost,
					Path:    "/menu/save",
					Handler: MenuSaveHandler(serverCtx),
				},
				{
					// 菜单管理
					Method:  http.MethodGet,
					Path:    "/menus",
					Handler: MenusHandler(serverCtx),
				},
				{
					// 权限保存
					Method:  http.MethodPost,
					Path:    "/prem/save",
					Handler: PremSaveHandler(serverCtx),
				},
				{
					// 角色管理
					Method:  http.MethodGet,
					Path:    "/roles",
					Handler: RolesHandler(serverCtx),
				},
				{
					// 标签列表
					Method:  http.MethodGet,
					Path:    "/tags",
					Handler: TagsHandler(serverCtx),
				},
				{
					// 图片上传
					Method:  http.MethodPost,
					Path:    "/upload",
					Handler: UploadHandler(serverCtx),
				},
				{
					// 用户管理
					Method:  http.MethodGet,
					Path:    "/users",
					Handler: UsersHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin"),
	)
}
