// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"

	"lxtian-blog/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 后台登录
				Method:  http.MethodPost,
				Path:    "/admin/login",
				Handler: LoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtMiddleware},
			[]rest.Route{
				{
					// 用户信息
					Method:  http.MethodGet,
					Path:    "/info",
					Handler: InfoHandler(serverCtx),
				},
				{
					// 菜单保存
					Method:  http.MethodPost,
					Path:    "/menu/save",
					Handler: MenuSaveHandler(serverCtx),
				},
				{
					// 菜单管理
					Method:  http.MethodGet,
					Path:    "/menus",
					Handler: MenusHandler(serverCtx),
				},
				{
					// 权限保存
					Method:  http.MethodPost,
					Path:    "/prem/save",
					Handler: PremSaveHandler(serverCtx),
				},
				{
					// 角色管理
					Method:  http.MethodGet,
					Path:    "/roles",
					Handler: RolesHandler(serverCtx),
				},
				{
					// 用户管理
					Method:  http.MethodGet,
					Path:    "/users",
					Handler: UsersHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/admin"),
	)
}
