# 网络配置
networks:
  local:
    driver: bridge

services:
  etcd:
    image: ${DOCKER_REGISTRY:-localhost:5000}/etcd:3.5.10  # 使用 etcd 的镜像
    hostname: etcd-v3
    environment:
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - etcd-data:/etcd-data  # 持久化存储
    networks:
      - local
    restart: always

  web-rpc:
    image: ${DOCKER_REGISTRY:-localhost:5000}/${DOCKER_ENV:?请设置docker环境}.web-rpc:latest
    build:
      context: .
      dockerfile: ./rpc/web/Dockerfile
    environment:
      - ETCD_ENDPOINTS=http://etcd-v3:2379  # 设置 etcd 地址
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - local
    restart: always

  gateway-api:
    image: ${DOCKER_REGISTRY:-localhost:5000}/${DOCKER_ENV:?请设置docker环境}.gateway-api:latest
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    ports:
      - ${DOCKER_GATEWAY_PORT:-8888}:8888
    environment:
      - ETCD_ENDPOINTS=http://etcd-v3:2379  # 设置 etcd 地址
    volumes:
      - ${PWD}/logs:/app/logs:cached
    networks:
      - local
    restart: always

volumes:
  etcd-data: {} # 定义持久化存储卷