# 网络配置
networks:
  local:
    driver: bridge

services:
  etcd:
    image: ${DOCKER_REGISTRY:-localhost:5000}/etcd:3.5.10  # 使用 etcd 的镜像
    hostname: etcd
    environment:
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - etcd-data:/etcd-data  # 持久化存储
    ports:
      - "2379:2379"  # 映射端口
    networks:
      - local
    restart: always

  web-rpc:
    image: ${DOCKER_REGISTRY:-localhost:5000}/${DOCKER_ENV:?请设置docker环境}.web-rpc:latest
    build:
      context: .
      dockerfile: ./rpc/web/Dockerfile
    environment:
      - ETCD_HOSTS=etcd:2379  # 设置 etcd 地址
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_TYPE=${REDIS_TYPE}
      - REDIS_PASS=${REDIS_PASS}
      - REDIS_TLS=${REDIS_TLS}
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - AccessKey=${AccessKey}
      - SecretKey=${SecretKey}
      - Bucket=${Bucket}
      - Domain=${Domain}
      - Region=${Region}
    volumes:
      - ${PWD}/rpc/web/logs:/app/logs:cached
    networks:
      - local
    restart: always

  user-rpc:
    image: ${DOCKER_REGISTRY:-localhost:5000}/${DOCKER_ENV:?请设置docker环境}.user-rpc:latest
    build:
      context: .
      dockerfile: ./rpc/user/Dockerfile
    environment:
      - ETCD_HOSTS=etcd:2379  # 设置 etcd 地址
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_TYPE=${REDIS_TYPE}
      - REDIS_PASS=${REDIS_PASS}
      - REDIS_TLS=${REDIS_TLS}
      - APPID=${APPID}
      - SECRET=${SECRET}
      - WS_HOST=${WS_HOST}
      - AccessKey=${AccessKey}
      - SecretKey=${SecretKey}
      - Bucket=${Bucket}
      - Domain=${Domain}
      - Region=${Region}
    volumes:
      - ${PWD}/rpc/user/logs:/app/logs:cached
    networks:
      - local
    restart: always

  payment-rpc:
    image: ${DOCKER_REGISTRY:-localhost:5000}/${DOCKER_ENV:?请设置docker环境}.payment-rpc:latest
    build:
      context: .
      dockerfile: ./rpc/payment/Dockerfile
    environment:
      - ETCD_HOSTS=etcd:2379  # 设置 etcd 地址
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_TYPE=${REDIS_TYPE}
      - REDIS_PASS=${REDIS_PASS}
      - REDIS_TLS=${REDIS_TLS}
      - MONGODB_HOST=${MONGODB_HOST}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - AccessKey=${AccessKey}
      - SecretKey=${SecretKey}
      - Bucket=${Bucket}
      - Domain=${Domain}
      - Region=${Region}
      - AlipayAppId=${AlipayAppId}
      - AlipayAppPrivateKey=${AlipayAppPrivateKey}
      - AlipayAlipayPublicKey=${AlipayAlipayPublicKey}
    volumes:
      - ${PWD}/rpc/payment/logs:/app/logs:cached
    networks:
      - local
    restart: always

  gateway-api:
    image: ${DOCKER_REGISTRY:-localhost:5000}/${DOCKER_ENV:?请设置docker环境}.gateway-api:latest
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    ports:
      - ${DOCKER_GATEWAY_PORT:-8888}:8888
    environment:
      - ETCD_HOSTS=etcd:2379  # 设置 etcd 地址
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_TYPE=${REDIS_TYPE}
      - REDIS_PASS=${REDIS_PASS}
      - REDIS_TLS=${REDIS_TLS}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - WS_HOST=${WS_HOST}
      - QQ_CLIENT_ID=${QQ_CLIENT_ID}
      - QQ_CLIENT_SECRET=${QQ_CLIENT_SECRET}
      - QQ_REDIRECT_URL=${QQ_REDIRECT_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - WEIBO_APP_ID=${WEIBO_APP_ID}
      - WEIBO_APP_SECRET=${WEIBO_APP_SECRET}
      - WEIBO_REDIRECT_URL=${WEIBO_REDIRECT_URL}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_REDIRECT_URL=${GITHUB_REDIRECT_URL}
    volumes:
      - ${PWD}/gateway/logs:/app/logs:cached
    networks:
      - local
    restart: always

  admin-api:
    image: ${DOCKER_REGISTRY:-localhost:5000}/${DOCKER_ENV:?请设置docker环境}.admin-api:latest
    build:
      context: .
      dockerfile: ./admin/Dockerfile
    ports:
      - ${DOCKER_ADMIN_PORT:-8090}:8090
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_TYPE=${REDIS_TYPE}
      - REDIS_PASS=${REDIS_PASS}
      - REDIS_TLS=${REDIS_TLS}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - WS_HOST=${WS_HOST}
      - AccessKey=${AccessKey}
      - SecretKey=${SecretKey}
      - Bucket=${Bucket}
      - Domain=${Domain}
      - Region=${Region}
    volumes:
      - ${PWD}/logs:/app/logs:cached
    networks:
      - local
    restart: always

volumes:
  etcd-data: {} # 定义持久化存储卷