// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: message.proto

package server

import (
	"context"

	"lxtian-blog/rpc/message/internal/logic"
	"lxtian-blog/rpc/message/internal/svc"
	"lxtian-blog/rpc/message/message"
)

type MessageServer struct {
	svcCtx *svc.ServiceContext
	message.UnimplementedMessageServer
}

func NewMessageServer(svcCtx *svc.ServiceContext) *MessageServer {
	return &MessageServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageServer) Ping(ctx context.Context, in *message.Request) (*message.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
