// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.2

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	txyTagFieldNames          = builder.RawFieldNames(&TxyTag{})
	txyTagRows                = strings.Join(txyTagFieldNames, ",")
	txyTagRowsExpectAutoSet   = strings.Join(stringx.Remove(txyTagFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	txyTagRowsWithPlaceHolder = strings.Join(stringx.Remove(txyTagFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	txyTagModel interface {
		Insert(ctx context.Context, data *TxyTag) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*TxyTag, error)
		Update(ctx context.Context, data *TxyTag) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultTxyTagModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TxyTag struct {
		Id          uint64         `db:"id"`
		Name        string         `db:"name"` // 标签名
		Keywords    sql.NullString `db:"keywords"`
		Description sql.NullString `db:"description"`
		CreatedAt   sql.NullTime   `db:"created_at"` // 创建时间
		UpdatedAt   sql.NullTime   `db:"updated_at"` // 更新时间
		DeletedAt   sql.NullTime   `db:"deleted_at"` // 删除时间
	}
)

func newTxyTagModel(conn sqlx.SqlConn) *defaultTxyTagModel {
	return &defaultTxyTagModel{
		conn:  conn,
		table: "`txy_tag`",
	}
}

func (m *defaultTxyTagModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTxyTagModel) FindOne(ctx context.Context, id uint64) (*TxyTag, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", txyTagRows, m.table)
	var resp TxyTag
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTxyTagModel) Insert(ctx context.Context, data *TxyTag) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, txyTagRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Keywords, data.Description, data.DeletedAt)
	return ret, err
}

func (m *defaultTxyTagModel) Update(ctx context.Context, data *TxyTag) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, txyTagRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Keywords, data.Description, data.DeletedAt, data.Id)
	return err
}

func (m *defaultTxyTagModel) tableName() string {
	return m.table
}
