// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLxtPaymentGoodsClassify = "lxt_payment_goods_classify"

// LxtPaymentGoodsClassify 商品分类表
type LxtPaymentGoodsClassify struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                      // 主键ID
	Name      string         `gorm:"column:name;not null;comment:名称" json:"name"`                                         // 名称
	Desc      string         `gorm:"column:desc;not null;comment:描述" json:"desc"`                                         // 描述
	Icon      string         `gorm:"column:icon;not null;comment:分类icon" json:"icon"`                                     // 分类icon
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName LxtPaymentGoodsClassify's table name
func (*LxtPaymentGoodsClassify) TableName() string {
	return TableNameLxtPaymentGoodsClassify
}
