// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLxtUserMembershipRenewal = "lxt_user_membership_renewals"

// LxtUserMembershipRenewal 会员续费记录表
type LxtUserMembershipRenewal struct {
	ID                   int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                       // 主键ID
	UserID               int64          `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                                  // 用户ID
	OrderID              *int64         `gorm:"column:order_id;comment:关联订单ID" json:"order_id"`                                       // 关联订单ID
	FromMembershipTypeID *int64         `gorm:"column:from_membership_type_id;comment:原会员类型ID（升级时使用）" json:"from_membership_type_id"` // 原会员类型ID（升级时使用）
	ToMembershipTypeID   int64          `gorm:"column:to_membership_type_id;not null;comment:目标会员类型ID" json:"to_membership_type_id"`  // 目标会员类型ID
	RenewalType          int32          `gorm:"column:renewal_type;not null;comment:续费类型：1同级续费2向上升级" json:"renewal_type"`             // 续费类型：1同级续费2向上升级
	BeforeStartTime      *time.Time     `gorm:"column:before_start_time;comment:续费前开始时间" json:"before_start_time"`                    // 续费前开始时间
	BeforeEndTime        *time.Time     `gorm:"column:before_end_time;comment:续费前结束时间" json:"before_end_time"`                        // 续费前结束时间
	AfterStartTime       time.Time      `gorm:"column:after_start_time;not null;comment:续费后开始时间" json:"after_start_time"`             // 续费后开始时间
	AfterEndTime         time.Time      `gorm:"column:after_end_time;not null;comment:续费后结束时间" json:"after_end_time"`                 // 续费后结束时间
	RemainingDays        *int32         `gorm:"column:remaining_days;comment:剩余天数（升级时计算用）" json:"remaining_days"`                     // 剩余天数（升级时计算用）
	CalculatedDays       int32          `gorm:"column:calculated_days;not null;comment:计算后的总天数" json:"calculated_days"`               // 计算后的总天数
	Amount               float64        `gorm:"column:amount;not null;comment:支付金额" json:"amount"`                                    // 支付金额
	CreatedAt            time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`  // 创建时间
	UpdatedAt            time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`  // 更新时间
	DeletedAt            gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                     // 删除时间
}

// TableName LxtUserMembershipRenewal's table name
func (*LxtUserMembershipRenewal) TableName() string {
	return TableNameLxtUserMembershipRenewal
}
