// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLxtPaymentRefund = "lxt_payment_refunds"

// LxtPaymentRefund 支付退款表
type LxtPaymentRefund struct {
	ID           int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                      // 主键ID
	RefundID     string         `gorm:"column:refund_id;not null;comment:退款ID" json:"refund_id"`                             // 退款ID
	PaymentID    string         `gorm:"column:payment_id;not null;comment:支付ID" json:"payment_id"`                           // 支付ID
	OrderSn      string         `gorm:"column:order_sn;not null;comment:订单编号" json:"order_sn"`                               // 订单编号
	OutTradeNo   string         `gorm:"column:out_trade_no;not null;comment:商户订单号" json:"out_trade_no"`                      // 商户订单号
	OutRequestNo string         `gorm:"column:out_request_no;not null;comment:退款单号" json:"out_request_no"`                   // 退款单号
	UserID       int64          `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                                 // 用户ID
	RefundAmount float64        `gorm:"column:refund_amount;not null;comment:退款金额" json:"refund_amount"`                     // 退款金额
	RefundFee    *float64       `gorm:"column:refund_fee;comment:退款手续费" json:"refund_fee"`                                   // 退款手续费
	RefundReason *string        `gorm:"column:refund_reason;comment:退款原因" json:"refund_reason"`                              // 退款原因
	Status       string         `gorm:"column:status;not null;default:PENDING;comment:退款状态" json:"status"`                   // 退款状态
	RefundStatus *string        `gorm:"column:refund_status;comment:支付宝退款状态" json:"refund_status"`                           // 支付宝退款状态
	GmtRefund    *time.Time     `gorm:"column:gmt_refund;comment:退款时间" json:"gmt_refund"`                                    // 退款时间
	CreatedAt    time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt    time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName LxtPaymentRefund's table name
func (*LxtPaymentRefund) TableName() string {
	return TableNameLxtPaymentRefund
}
