// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLxtUserMembershipType = "lxt_user_membership_types"

// LxtUserMembershipType 会员类型表
type LxtUserMembershipType struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                      // 主键ID
	Name          string         `gorm:"column:name;not null;comment:会员类型名称（月度会员、季度会员、年度会员）" json:"name"`                     // 会员类型名称（月度会员、季度会员、年度会员）
	Key           string         `gorm:"column:key;not null;comment:会员类型标识（monthly, quarterly, yearly）" json:"key"`           // 会员类型标识（monthly, quarterly, yearly）
	Days          int32          `gorm:"column:days;not null;comment:会员天数" json:"days"`                                       // 会员天数
	Price         float64        `gorm:"column:price;not null;comment:价格" json:"price"`                                       // 价格
	OriginalPrice float64        `gorm:"column:original_price;not null;comment:原价" json:"original_price"`                     // 原价
	Discount      float64        `gorm:"column:discount;not null;comment:折扣价" json:"discount"`                                // 折扣价
	Period        string         `gorm:"column:period;not null;comment:单位" json:"period"`                                     // 单位
	Popular       int32          `gorm:"column:popular;not null;comment:是否推荐：0否1是" json:"popular"`                            // 是否推荐：0否1是
	Permissions   *string        `gorm:"column:permissions;comment:会员权限" json:"permissions"`                                  // 会员权限
	Description   *string        `gorm:"column:description;comment:会员描述" json:"description"`                                  // 会员描述
	Status        int32          `gorm:"column:status;not null;default:1;comment:状态：1启用0禁用" json:"status"`                    // 状态：1启用0禁用
	CreatedAt     time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt     time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName LxtUserMembershipType's table name
func (*LxtUserMembershipType) TableName() string {
	return TableNameLxtUserMembershipType
}
