// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLxtPaymentConfig = "lxt_payment_configs"

// LxtPaymentConfig 支付配置表
type LxtPaymentConfig struct {
	ID              int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                      // 主键ID
	AppID           string         `gorm:"column:app_id;not null;comment:应用ID" json:"app_id"`                                   // 应用ID
	AppName         string         `gorm:"column:app_name;not null;comment:应用名称" json:"app_name"`                               // 应用名称
	AppPrivateKey   string         `gorm:"column:app_private_key;not null;comment:应用私钥" json:"app_private_key"`                 // 应用私钥
	AlipayPublicKey string         `gorm:"column:alipay_public_key;not null;comment:支付宝公钥" json:"alipay_public_key"`            // 支付宝公钥
	GatewayURL      string         `gorm:"column:gateway_url;not null;comment:支付宝网关地址" json:"gateway_url"`                      // 支付宝网关地址
	IsProd          bool           `gorm:"column:is_prod;not null;comment:是否生产环境" json:"is_prod"`                               // 是否生产环境
	IsEnabled       bool           `gorm:"column:is_enabled;not null;default:1;comment:是否启用" json:"is_enabled"`                 // 是否启用
	NotifyURL       *string        `gorm:"column:notify_url;comment:默认通知地址" json:"notify_url"`                                  // 默认通知地址
	ReturnURL       *string        `gorm:"column:return_url;comment:默认返回地址" json:"return_url"`                                  // 默认返回地址
	CreatedAt       time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt       time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName LxtPaymentConfig's table name
func (*LxtPaymentConfig) TableName() string {
	return TableNameLxtPaymentConfig
}
