// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLxtPaymentNotify = "lxt_payment_notifies"

// LxtPaymentNotify 支付通知记录表
type LxtPaymentNotify struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                      // 主键ID
	NotifyID      string         `gorm:"column:notify_id;not null;comment:通知ID" json:"notify_id"`                             // 通知ID
	PaymentID     string         `gorm:"column:payment_id;not null;comment:支付ID" json:"payment_id"`                           // 支付ID
	NotifyType    string         `gorm:"column:notify_type;not null;comment:通知类型：PAYMENT/REFUND" json:"notify_type"`          // 通知类型：PAYMENT/REFUND
	NotifyData    string         `gorm:"column:notify_data;not null;comment:通知数据" json:"notify_data"`                         // 通知数据
	Sign          *string        `gorm:"column:sign;comment:签名" json:"sign"`                                                  // 签名
	SignType      *string        `gorm:"column:sign_type;comment:签名类型" json:"sign_type"`                                      // 签名类型
	VerifyStatus  string         `gorm:"column:verify_status;not null;default:PENDING;comment:验证状态" json:"verify_status"`     // 验证状态
	ProcessStatus string         `gorm:"column:process_status;not null;default:PENDING;comment:处理状态" json:"process_status"`   // 处理状态
	ClientIP      *string        `gorm:"column:client_ip;comment:客户端IP" json:"client_ip"`                                     // 客户端IP
	ErrorMessage  *string        `gorm:"column:error_message;comment:错误信息" json:"error_message"`                              // 错误信息
	ProcessedAt   *time.Time     `gorm:"column:processed_at;comment:处理时间" json:"processed_at"`                                // 处理时间
	CreatedAt     time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt     time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName LxtPaymentNotify's table name
func (*LxtPaymentNotify) TableName() string {
	return TableNameLxtPaymentNotify
}
