// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLxtPaymentOrder = "lxt_payment_orders"

// LxtPaymentOrder 支付订单表
type LxtPaymentOrder struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                      // 主键ID
	PaymentID     string         `gorm:"column:payment_id;not null;comment:支付ID" json:"payment_id"`                           // 支付ID
	OrderSn       string         `gorm:"column:order_sn;not null;comment:订单编号" json:"order_sn"`                               // 订单编号
	OutTradeNo    string         `gorm:"column:out_trade_no;not null;comment:商户订单号" json:"out_trade_no"`                      // 商户订单号
	GoodsID       int32          `gorm:"column:goods_id;not null;comment:商品ID" json:"goods_id"`                               // 商品ID
	Quantity      int32          `gorm:"column:quantity;not null;default:1;comment:商品数量" json:"quantity"`                     // 商品数量
	VipID         int32          `gorm:"column:vip_id;not null;comment:会员id" json:"vip_id"`                                   // 会员id
	BuyType       int32          `gorm:"column:buy_type;not null;comment:购买类型：1:商品消费2:购买会员" json:"buy_type"`                  // 购买类型：1:商品消费2:购买会员
	UserID        int64          `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                                 // 用户ID
	Amount        float64        `gorm:"column:amount;not null;comment:支付金额" json:"amount"`                                   // 支付金额
	Subject       string         `gorm:"column:subject;not null;comment:订单标题" json:"subject"`                                 // 订单标题
	Body          *string        `gorm:"column:body;comment:订单描述" json:"body"`                                                // 订单描述
	PayType       int32          `gorm:"column:pay_type;not null;comment:支付类型：1支付宝2微信3银行卡" json:"pay_type"`                   // 支付类型：1支付宝2微信3银行卡
	Status        string         `gorm:"column:status;not null;default:PENDING;comment:支付状态" json:"status"`                   // 支付状态
	TradeNo       string         `gorm:"column:trade_no;not null;comment:支付宝交易号" json:"trade_no"`                             // 支付宝交易号
	TradeStatus   string         `gorm:"column:trade_status;not null;comment:支付宝交易状态" json:"trade_status"`                    // 支付宝交易状态
	BuyerUserID   string         `gorm:"column:buyer_user_id;not null;comment:买家支付宝用户ID" json:"buyer_user_id"`                // 买家支付宝用户ID
	BuyerLogonID  string         `gorm:"column:buyer_logon_id;not null;comment:买家支付宝账号" json:"buyer_logon_id"`                // 买家支付宝账号
	ReceiptAmount float64        `gorm:"column:receipt_amount;not null;comment:实收金额" json:"receipt_amount"`                   // 实收金额
	ProductCode   *string        `gorm:"column:product_code;default:FAST_INSTANT_TRADE_PAY;comment:产品码" json:"product_code"`  // 产品码
	ReturnURL     string         `gorm:"column:return_url;not null;comment:支付成功跳转地址" json:"return_url"`                       // 支付成功跳转地址
	NotifyURL     string         `gorm:"column:notify_url;not null;comment:支付结果异步通知地址" json:"notify_url"`                     // 支付结果异步通知地址
	Timeout       string         `gorm:"column:timeout;not null;comment:订单超时时间" json:"timeout"`                               // 订单超时时间
	ClientIP      string         `gorm:"column:client_ip;not null;comment:客户端IP" json:"client_ip"`                            // 客户端IP
	Remark        string         `gorm:"column:remark;not null;comment:备注" json:"remark"`                                     // 备注
	PayTime       *time.Time     `gorm:"column:pay_time;comment:支付时间" json:"pay_time"`                                        // 支付时间
	CloseTime     *time.Time     `gorm:"column:close_time;comment:交易关闭时间" json:"close_time"`                                  // 交易关闭时间
	CreatedAt     time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt     time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName LxtPaymentOrder's table name
func (*LxtPaymentOrder) TableName() string {
	return TableNameLxtPaymentOrder
}
