// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLxtUserMembershipLevel = "lxt_user_membership_levels"

// LxtUserMembershipLevel 会员等级表
type LxtUserMembershipLevel struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                      // 主键ID
	Level      int32          `gorm:"column:level;not null;comment:等级" json:"level"`                                       // 等级
	Name       string         `gorm:"column:name;not null;comment:等级名称" json:"name"`                                       // 等级名称
	MinDays    int32          `gorm:"column:min_days;not null;comment:最少累计会员天数" json:"min_days"`                           // 最少累计会员天数
	MaxDays    *int32         `gorm:"column:max_days;comment:最多累计会员天数（NULL表示无上限）" json:"max_days"`                         // 最多累计会员天数（NULL表示无上限）
	Icon       *string        `gorm:"column:icon;comment:等级图标" json:"icon"`                                                // 等级图标
	Privileges *string        `gorm:"column:privileges;comment:等级特权（JSON格式）" json:"privileges"`                            // 等级特权（JSON格式）
	CreatedAt  time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt  time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName LxtUserMembershipLevel's table name
func (*LxtUserMembershipLevel) TableName() string {
	return TableNameLxtUserMembershipLevel
}
