// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLxtUserMembershipPermission = "lxt_user_membership_permissions"

// LxtUserMembershipPermission 会员权限表
type LxtUserMembershipPermission struct {
	ID               int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                      // 主键ID
	MembershipTypeID int64          `gorm:"column:membership_type_id;not null;comment:会员类型ID" json:"membership_type_id"`         // 会员类型ID
	PermissionKey    string         `gorm:"column:permission_key;not null;comment:权限标识" json:"permission_key"`                   // 权限标识
	PermissionName   string         `gorm:"column:permission_name;not null;comment:权限名称" json:"permission_name"`                 // 权限名称
	PermissionDesc   *string        `gorm:"column:permission_desc;comment:权限描述" json:"permission_desc"`                          // 权限描述
	CreatedAt        time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt        time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName LxtUserMembershipPermission's table name
func (*LxtUserMembershipPermission) TableName() string {
	return TableNameLxtUserMembershipPermission
}
