// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTxyUser = "txy_user"

// TxyUser mapped from table <txy_user>
type TxyUser struct {
	ID            int32          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键id" json:"id"`                           // 主键id
	UID           int32          `gorm:"column:uid;not null;comment:关联的本站用户id" json:"uid"`                                         // 关联的本站用户id
	Username      *string        `gorm:"column:username;comment:用户名" json:"username"`                                              // 用户名
	Password      string         `gorm:"column:password;not null;comment:密码" json:"password"`                                      // 密码
	Email         string         `gorm:"column:email;not null;comment:邮箱" json:"email"`                                            // 邮箱
	Type          int32          `gorm:"column:type;not null;default:1;comment:类型 ：0账号,1QQ ,2新浪微博, 3微信, 4小程序,5github" json:"type"` // 类型 ：0账号,1QQ ,2新浪微博, 3微信, 4小程序,5github
	Nickname      string         `gorm:"column:nickname;not null;comment:第三方昵称" json:"nickname"`                                   // 第三方昵称
	HeadImg       string         `gorm:"column:head_img;not null;comment:头像" json:"head_img"`                                      // 头像
	Openid        string         `gorm:"column:openid;not null;comment:第三方用户id" json:"openid"`                                     // 第三方用户id
	AccessToken   string         `gorm:"column:access_token;not null;comment:access_token token" json:"access_token"`              // access_token token
	SessionKey    string         `gorm:"column:session_key;not null;comment:session_key" json:"session_key"`                       // session_key
	MiniappOpenid string         `gorm:"column:miniapp_openid;not null;comment:小程序openid" json:"miniapp_openid"`                   // 小程序openid
	Unionid       string         `gorm:"column:unionid;not null;comment:微信 unionid" json:"unionid"`                                // 微信 unionid
	LastLoginTime int32          `gorm:"column:last_login_time;not null;comment:最后登录时间" json:"last_login_time"`                    // 最后登录时间
	LastLoginIP   string         `gorm:"column:last_login_ip;not null;comment:最后登录ip" json:"last_login_ip"`                        // 最后登录ip
	LoginTimes    int32          `gorm:"column:login_times;not null;comment:登录次数" json:"login_times"`                              // 登录次数
	Status        int32          `gorm:"column:status;not null;default:1;comment:状态" json:"status"`                                // 状态
	IsAdmin       int32          `gorm:"column:is_admin;not null;comment:是否是admin" json:"is_admin"`                                // 是否是admin
	Gold          int32          `gorm:"column:gold;not null;comment:金币" json:"gold"`                                              // 金币
	Score         int32          `gorm:"column:score;not null;comment:可用积分" json:"score"`                                          // 可用积分
	Conscore      int32          `gorm:"column:conscore;not null;comment:已经消费积分" json:"conscore"`                                  // 已经消费积分
	CreatedAt     *time.Time     `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                         // 创建时间
	UpdatedAt     *time.Time     `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                                         // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                         // 删除时间
}

// TableName TxyUser's table name
func (*TxyUser) TableName() string {
	return TableNameTxyUser
}
