// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTxyOrder = "txy_order"

// TxyOrder mapped from table <txy_order>
type TxyOrder struct {
	ID         int32   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PaymentID  string  `gorm:"column:payment_id;not null;comment:支付ID" json:"payment_id"`           // 支付ID
	OutTradeNo string  `gorm:"column:out_trade_no;not null;comment:商户订单号" json:"out_trade_no"`      // 商户订单号
	OrderSn    string  `gorm:"column:order_sn;not null;comment:订单号" json:"order_sn"`                // 订单号
	PayMoney   float64 `gorm:"column:pay_money;not null;comment:支付金额" json:"pay_money"`             // 支付金额
	PayType    int32   `gorm:"column:pay_type;not null;comment:1:捐赠2:购买模板3:直接消费" json:"pay_type"`   // 1:捐赠2:购买模板3:直接消费
	UserID     int32   `gorm:"column:user_id;not null;comment:用户id" json:"user_id"`                 // 用户id
	Status     int32   `gorm:"column:status;not null;comment:支付状态：0待支付1已支付2已发货3交易完成" json:"status"` // 支付状态：0待支付1已支付2已发货3交易完成
	GoodsName  string  `gorm:"column:goods_name;not null;comment:商品名称" json:"goods_name"`           // 商品名称
	Ctime      int32   `gorm:"column:ctime;not null;comment:创建时间" json:"ctime"`                     // 创建时间
	Remark     *string `gorm:"column:remark" json:"remark"`
	IP         string  `gorm:"column:ip;not null;comment:ip地址" json:"ip"` // ip地址
}

// TableName TxyOrder's table name
func (*TxyOrder) TableName() string {
	return TableNameTxyOrder
}
