// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: web.proto

package webclient

import (
	"context"

	"lxtian-blog/rpc/web/web"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = web.Request
	Response = web.Response

	Web interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultWeb struct {
		cli zrpc.Client
	}
)

func NewWeb(cli zrpc.Client) Web {
	return &defaultWeb{
		cli: cli,
	}
}

func (m *defaultWeb) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := web.NewWebClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
