// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "lxtian-blog/gateway/internal/handler/user"
	web "lxtian-blog/gateway/internal/handler/web"
	"lxtian-blog/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: user.InfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 文章详情
				Method:  http.MethodGet,
				Path:    "/article/:id",
				Handler: web.ArticleHandler(serverCtx),
			},
			{
				// 文章列表
				Method:  http.MethodGet,
				Path:    "/article/list",
				Handler: web.ArticleListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/web"),
	)
}
