// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: message.proto

package messageclient

import (
	"context"

	"lxtian-blog/rpc/message/message"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = message.Request
	Response = message.Response

	Message interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultMessage struct {
		cli zrpc.Client
	}
)

func NewMessage(cli zrpc.Client) Message {
	return &defaultMessage{
		cli: cli,
	}
}

func (m *defaultMessage) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := message.NewMessageClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
