// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: web.proto

package web

import (
	"context"

	"lxtian-blog/rpc/web/web"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ArticleLikeReq     = web.ArticleLikeReq
	ArticleLikeResp    = web.ArticleLikeResp
	ArticleListReq     = web.ArticleListReq
	ArticleListResp    = web.ArticleListResp
	ArticleReq         = web.ArticleReq
	ArticleResp        = web.ArticleResp
	BookChapterReq     = web.BookChapterReq
	BookChapterResp    = web.BookChapterResp
	BookListReq        = web.BookListReq
	BookListResp       = web.BookListResp
	BookReq            = web.BookReq
	BookResp           = web.BookResp
	CategoryListReq    = web.CategoryListReq
	CategoryListResp   = web.CategoryListResp
	ChatListReq        = web.ChatListReq
	ChatListResp       = web.ChatListResp
	ColumnListReq      = web.ColumnListReq
	ColumnListResp     = web.ColumnListResp
	CommentListReq     = web.CommentListReq
	CommentListResp    = web.CommentListResp
	DocsCategoriesReq  = web.DocsCategoriesReq
	DocsCategoriesResp = web.DocsCategoriesResp
	DocsLatestReq      = web.DocsLatestReq
	DocsLatestResp     = web.DocsLatestResp
	DocsListReq        = web.DocsListReq
	DocsListResp       = web.DocsListResp
	DocsPopularReq     = web.DocsPopularReq
	DocsPopularResp    = web.DocsPopularResp
	DocsReq            = web.DocsReq
	DocsResp           = web.DocsResp
	DocsStatsReq       = web.DocsStatsReq
	DocsStatsResp      = web.DocsStatsResp
	DocsTagsReq        = web.DocsTagsReq
	DocsTagsResp       = web.DocsTagsResp
	OrderListReq       = web.OrderListReq
	OrderListResp      = web.OrderListResp
	OrderStatReq       = web.OrderStatReq
	OrderStatResp      = web.OrderStatResp
	TagsListReq        = web.TagsListReq
	TagsListResp       = web.TagsListResp

	Web interface {
		ArticleList(ctx context.Context, in *ArticleListReq, opts ...grpc.CallOption) (*ArticleListResp, error)
		Article(ctx context.Context, in *ArticleReq, opts ...grpc.CallOption) (*ArticleResp, error)
		ArticleLike(ctx context.Context, in *ArticleLikeReq, opts ...grpc.CallOption) (*ArticleLikeResp, error)
		CategoryList(ctx context.Context, in *CategoryListReq, opts ...grpc.CallOption) (*CategoryListResp, error)
		ChatList(ctx context.Context, in *ChatListReq, opts ...grpc.CallOption) (*ChatListResp, error)
		CommentList(ctx context.Context, in *CommentListReq, opts ...grpc.CallOption) (*CommentListResp, error)
		OrderList(ctx context.Context, in *OrderListReq, opts ...grpc.CallOption) (*OrderListResp, error)
		OrderStat(ctx context.Context, in *OrderStatReq, opts ...grpc.CallOption) (*OrderStatResp, error)
		TagsList(ctx context.Context, in *TagsListReq, opts ...grpc.CallOption) (*TagsListResp, error)
		ColumnList(ctx context.Context, in *ColumnListReq, opts ...grpc.CallOption) (*ColumnListResp, error)
		BookList(ctx context.Context, in *BookListReq, opts ...grpc.CallOption) (*BookListResp, error)
		Book(ctx context.Context, in *BookReq, opts ...grpc.CallOption) (*BookResp, error)
		BookChapter(ctx context.Context, in *BookChapterReq, opts ...grpc.CallOption) (*BookChapterResp, error)
		DocsList(ctx context.Context, in *DocsListReq, opts ...grpc.CallOption) (*DocsListResp, error)
		DocsCategories(ctx context.Context, in *DocsCategoriesReq, opts ...grpc.CallOption) (*DocsCategoriesResp, error)
		DocsStats(ctx context.Context, in *DocsStatsReq, opts ...grpc.CallOption) (*DocsStatsResp, error)
		DocsPopular(ctx context.Context, in *DocsPopularReq, opts ...grpc.CallOption) (*DocsPopularResp, error)
		DocsLatest(ctx context.Context, in *DocsLatestReq, opts ...grpc.CallOption) (*DocsLatestResp, error)
		DocsTags(ctx context.Context, in *DocsTagsReq, opts ...grpc.CallOption) (*DocsTagsResp, error)
		Docs(ctx context.Context, in *DocsReq, opts ...grpc.CallOption) (*DocsResp, error)
	}

	defaultWeb struct {
		cli zrpc.Client
	}
)

func NewWeb(cli zrpc.Client) Web {
	return &defaultWeb{
		cli: cli,
	}
}

func (m *defaultWeb) ArticleList(ctx context.Context, in *ArticleListReq, opts ...grpc.CallOption) (*ArticleListResp, error) {
	client := web.NewWebClient(m.cli.Conn())
	return client.ArticleList(ctx, in, opts...)
}

func (m *defaultWeb) Article(ctx context.Context, in *ArticleReq, opts ...grpc.CallOption) (*ArticleResp, error) {
	client := web.NewWebClient(m.cli.Conn())
	return client.Article(ctx, in, opts...)
}

func (m *defaultWeb) ArticleLike(ctx context.Context, in *ArticleLikeReq, opts ...grpc.CallOption) (*ArticleLikeResp, error) {
	client := web.NewWebClient(m.cli.Conn())
	return client.ArticleLike(ctx, in, opts...)
}

func (m *defaultWeb) CategoryList(ctx context.Context, in *CategoryListReq, opts ...grpc.CallOption) (*CategoryListResp, error) {
	client := web.NewWebClient(m.cli.Conn())
	return client.CategoryList(ctx, in, opts...)
}

func (m *defaultWeb) ChatList(ctx context.Context, in *ChatListReq, opts ...grpc.CallOption) (*ChatListResp, error) {
	client := web.NewWebClient(m.cli.Conn())
	return client.ChatList(ctx, in, opts...)
}

func (m *defaultWeb) CommentList(ctx context.Context, in *CommentListReq, opts ...grpc.CallOption) (*CommentListResp, error) {
	client := web.NewWebClient(m.cli.Conn())
	return client.CommentList(ctx, in, opts...)
}

func (m *defaultWeb) OrderList(ctx context.Context, in *OrderListReq, opts ...grpc.CallOption) (*OrderListResp, error) {
	client := web.NewWebClient(m.cli.Conn())
	return client.OrderList(ctx, in, opts...)
}

func (m *defaultWeb) OrderStat(ctx context.Context, in *OrderStatReq, opts ...grpc.CallOption) (*OrderStatResp, error) {
	client := web.NewWebClient(m.cli.Conn())
	return client.OrderStat(ctx, in, opts...)
}

func (m *defaultWeb) TagsList(ctx context.Context, in *TagsListReq, opts ...grpc.CallOption) (*TagsListResp, error) {
	client := web.NewWebClient(m.cli.Conn())
	return client.TagsList(ctx, in, opts...)
}

func (m *defaultWeb) ColumnList(ctx context.Context, in *ColumnListReq, opts ...grpc.CallOption) (*ColumnListResp, error) {
	client := web.NewWebClient(m.cli.Conn())
	return client.ColumnList(ctx, in, opts...)
}

func (m *defaultWeb) BookList(ctx context.Context, in *BookListReq, opts ...grpc.CallOption) (*BookListResp, error) {
	client := web.NewWebClient(m.cli.Conn())
	return client.BookList(ctx, in, opts...)
}

func (m *defaultWeb) Book(ctx context.Context, in *BookReq, opts ...grpc.CallOption) (*BookResp, error) {
	client := web.NewWebClient(m.cli.Conn())
	return client.Book(ctx, in, opts...)
}

func (m *defaultWeb) BookChapter(ctx context.Context, in *BookChapterReq, opts ...grpc.CallOption) (*BookChapterResp, error) {
	client := web.NewWebClient(m.cli.Conn())
	return client.BookChapter(ctx, in, opts...)
}

func (m *defaultWeb) DocsList(ctx context.Context, in *DocsListReq, opts ...grpc.CallOption) (*DocsListResp, error) {
	client := web.NewWebClient(m.cli.Conn())
	return client.DocsList(ctx, in, opts...)
}

func (m *defaultWeb) DocsCategories(ctx context.Context, in *DocsCategoriesReq, opts ...grpc.CallOption) (*DocsCategoriesResp, error) {
	client := web.NewWebClient(m.cli.Conn())
	return client.DocsCategories(ctx, in, opts...)
}

func (m *defaultWeb) DocsStats(ctx context.Context, in *DocsStatsReq, opts ...grpc.CallOption) (*DocsStatsResp, error) {
	client := web.NewWebClient(m.cli.Conn())
	return client.DocsStats(ctx, in, opts...)
}

func (m *defaultWeb) DocsPopular(ctx context.Context, in *DocsPopularReq, opts ...grpc.CallOption) (*DocsPopularResp, error) {
	client := web.NewWebClient(m.cli.Conn())
	return client.DocsPopular(ctx, in, opts...)
}

func (m *defaultWeb) DocsLatest(ctx context.Context, in *DocsLatestReq, opts ...grpc.CallOption) (*DocsLatestResp, error) {
	client := web.NewWebClient(m.cli.Conn())
	return client.DocsLatest(ctx, in, opts...)
}

func (m *defaultWeb) DocsTags(ctx context.Context, in *DocsTagsReq, opts ...grpc.CallOption) (*DocsTagsResp, error) {
	client := web.NewWebClient(m.cli.Conn())
	return client.DocsTags(ctx, in, opts...)
}

func (m *defaultWeb) Docs(ctx context.Context, in *DocsReq, opts ...grpc.CallOption) (*DocsResp, error) {
	client := web.NewWebClient(m.cli.Conn())
	return client.Docs(ctx, in, opts...)
}
