# 安全配置文件
RateLimit:
  # 通用接口限流
  Default:
    WindowSize: "1m"      # 时间窗口：1分钟
    MaxRequests: 60       # 最大请求数：60次
    KeyPrefix: "rate_limit"
  
  # 文章详情限流
  Article:
    WindowSize: "1m"      # 时间窗口：1分钟
    MaxRequests: 30       # 最大请求数：30次
    KeyPrefix: "article_rate"
  
  # 分类列表限流
  Category:
    WindowSize: "1m"      # 时间窗口：1分钟
    MaxRequests: 20       # 最大请求数：20次
    KeyPrefix: "category_rate"
  
  # 用户相关接口限流
  User:
    WindowSize: "1m"      # 时间窗口：1分钟
    MaxRequests: 100      # 最大请求数：100次
    KeyPrefix: "user_rate"
  
  # 管理接口限流
  Admin:
    WindowSize: "1m"      # 时间窗口：1分钟
    MaxRequests: 10       # 最大请求数：10次
    KeyPrefix: "admin_rate"
