// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type ArticleListReq struct {
	Cid      uint `form:"cid"`
	Page     uint `form:"page"`
	PageSize uint `form:"page_size"`
}

type ArticleListResp struct {
	Total uint `json:"total"`
}
