// Code generated by goctl. DO NOT EDIT.
package types

type Article struct {
	Id      int    `json:"id"`
	Title   string `json:"title"`
	Author  string `json:"author"`
	Content string `json:"content"`
}

type ArticleListReq struct {
	Cid      int `form:"cid"`
	Page     int `form:"page"`
	PageSize int `form:"page_size"`
}

type ArticleListResp struct {
	Page     int       `json:"page"`
	PageSize int       `json:"page_size"`
	List     []Article `json:"list"`
	Total    int       `json:"total"`
}
